version: "3.11"

x-global-environment: &global
  env_file:
    - envs/.env # env file - NOT committed to Git

services:
  # Caddy reverse proxy - web-facing SSL server
  caddy:
    <<: *global # this will inherit all the envs from x-global-environment
    depends_on:
      - django
    image: caddy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - caddy-data:/data/
      - caddy-data:/config/
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./staticdocs:/srv/staticdocs

  # Django web application
  django: &django
    <<: *global # this will inherit all the envs from x-global-environment
    ports:
      - 8003:8003
    build: .
    depends_on:
      - postgis
    volumes:
      - .:/app/
    command: >
      sh -c "python -u manage.py collectstatic --noinput &&
            python -u manage.py makemigrations &&
            python -u manage.py migrate &&
            echo $$DJANGO_STARTUP_COMMAND &&
            $$DJANGO_STARTUP_COMMAND"
    restart: always

  # PostgreSQL with PostGIS extension
  postgis:
    <<: *global # this will inherit all the envs from x-global-environment
    image: postgis/postgis:15-3.3
    volumes:
      - postgis-data:/var/lib/postgresql/data
    restart: always

  mkdocs:
    <<: *django # this will inherit all the settings from the django service
    ports:
      - 8004:8004
    command: >
      sh -c "mkdocs build --config-file documentation/mkdocs.yml &&
        mkdocs serve --config-file documentation/mkdocs.yml"
    restart: always

volumes:
  caddy-data:
  postgis-data:
