# Generated by Django 4.2.11 on 2024-06-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0002_seed_abstraction_levels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="ods_code",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="paediatricdiabetesunit",
            name="pz_code",
            field=models.CharField(
                max_length=5,
                unique=True,
                verbose_name="Paediatric Diabetes Unit PZ Number",
            ),
        ),
    ]
