# Generated by Django 4.2.11 on 2024-06-29 15:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0003_alter_organisation_ods_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JerseyBoundaries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objectid", models.IntegerField()),
                ("shape_id", models.CharField(max_length=18)),
                ("area_ha", models.FloatField()),
                ("remark", models.CharField(blank=True, max_length=20, null=True)),
                ("code_06", models.CharField(blank=True, max_length=3, null=True)),
                ("shape_leng", models.FloatField()),
                ("shape_area", models.FloatField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
    ]
