# Generated by Django 4.2.11 on 2024-06-30 12:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0004_jerseyboundaries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="bng_e",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="bng_n",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=27700
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="globalid",
            field=models.CharField(blank=True, max_length=38, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="welsh_name",
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
