# Generated by Django 4.2.11 on 2024-11-29 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0006_paediatricdiabetesnetwork_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JerseyBoundaries",
        ),
    ]
