# Generated by Django 4.2.11 on 2024-11-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0007_delete_jerseyboundaries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="long",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
