# Generated by Django 4.2.11 on 2024-11-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0010_refactor_jersey_boundary_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trust",
            name="ods_code",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
