# Generated by Django 4.2.11 on 2024-12-08 13:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0011_alter_trust_ods_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalAuthorityDistrict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lad24cd", models.CharField(max_length=9)),
                ("lad24nm", models.CharField(max_length=36)),
                ("lad24nmw", models.CharField(blank=True, max_length=24, null=True)),
                ("bng_e", models.BigIntegerField()),
                ("bng_n", models.BigIntegerField()),
                ("long", models.FloatField()),
                ("lat", models.FloatField()),
                ("globalid", models.CharField(max_length=38)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=27700),
                ),
                ("publication_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Local Authority District",
                "verbose_name_plural": "Local Authority Districts",
                "ordering": ("lad24nm",),
                "indexes": [
                    models.Index(
                        fields=["lad24cd"], name="hospitals_l_lad24cd_eb5d42_idx"
                    )
                ],
            },
        ),
    ]
