# Generated by Django 4.2.11 on 2024-12-08 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0013_seed_local_authority_districts_boundaries"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="local_authority_district",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="local_authority_district_organisations",
                to="hospitals.localauthoritydistrict",
            ),
        ),
    ]
