# Generated by Django 4.2.11 on 2024-12-08 14:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0014_organisation_local_authority_district"),
    ]

    operations = [
        migrations.CreateModel(
            name="LowerLayerSuperOutputArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lsoa11cd", models.CharField(max_length=9)),
                ("lsoa11nm", models.CharField(max_length=50)),
                ("lsoa11nmw", models.CharField(blank=True, max_length=50, null=True)),
                ("bng_e", models.BigIntegerField()),
                ("bng_n", models.BigIntegerField()),
                ("long", models.FloatField()),
                ("lat", models.FloatField()),
                ("globalid", models.CharField(max_length=38)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=27700),
                ),
                ("publication_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Local Authority District",
                "verbose_name_plural": "Local Authority Districts",
                "ordering": ("lsoa11nm",),
                "indexes": [
                    models.Index(
                        fields=["lsoa11cd"], name="hospitals_l_lsoa11c_c42f95_idx"
                    )
                ],
            },
        ),
    ]
