# Generated by Django 4.2.11 on 2024-12-08 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0016_seed_lsoa_boundaries"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="lower_layer_super_output_area",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lower_layer_super_output_area_organisations",
                to="hospitals.lowerlayersuperoutputarea",
            ),
        ),
    ]
