# Generated by Django 4.2.17 on 2025-03-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0017_organisation_lower_layer_super_output_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="paediatricdiabetesunit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
        ),
    ]
