# Generated by Django 4.2.17 on 2025-03-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0018_paediatricdiabetesunit_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="paediatricdiabetesunit",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
    ]
