# Generated by Django 5.2.1 on 2025-07-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0019_paediatricdiabetesunit_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="paediatricdiabetesunit",
            name="unit_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Name for the unit if different from the primary organisation for the parent",
            ),
        ),
    ]
