# Generated by Django 5.2.13 on 2026-04-20 11:34

from django.db import migrations, models


def load(apps, schema_editor, verbose=True):
    Country = apps.get_model("hospitals", "Country")

    Country.objects.get_or_create(
        boundary_identifier="M83000003",
        defaults={
            "name": "Isle of Man"
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0020_paediatricdiabetesunit_unit_name'),
    ]

    operations = [
        migrations.RunPython(
            code=rcpch_nhs_organisations.hospitals.migrations.0021_isle_of_man.load,
        ),
        migrations.AlterField(
            model_name='organisation',
            name='website',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
