# Generated by Django 5.2.13 on 2026-04-20 11:23

from django.db import migrations

def load(apps, schema_editor, verbose=True):
    Country = apps.get_model("hospitals", "Country")

    Country.objects.get_or_create(
        boundary_identifier="M83000003",
        defaults={
            "name": "Isle of Man"
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0020_paediatricdiabetesunit_unit_name"),
    ]

    operations = [migrations.RunPython(load)]
