# Generated by Django 5.2.8 on 2026-01-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0020_paediatricdiabetesunit_unit_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="inactive_paediatric_diabetes_units",
            field=models.ManyToManyField(
                blank=True, to="hospitals.paediatricdiabetesunit"
            ),
        ),
    ]
