# Generated by Django 5.2.1 on 2026-08-04 14:29

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0021_isle_of_man"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valid_from",
                    models.DateField(
                        help_text="The date from which this state of the Organisation was in force.",
                        verbose_name="Valid from",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="The date on which this state ceased to be in force. NULL means this is the current state.",
                        null=True,
                        verbose_name="Valid to",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "website",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "address1",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "address2",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "address3",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "county",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                ("longitude", models.FloatField(blank=True, default=None, null=True)),
                (
                    "postcode",
                    models.CharField(
                        blank=True, default=None, max_length=10, null=True
                    ),
                ),
                (
                    "geocode_coordinates",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, default=None, null=True, srid=27700
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("published_at", models.DateField(blank=True, default=None, null=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        help_text="The Organisation this version is a snapshot of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="hospitals.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation version",
                "verbose_name_plural": "Organisation versions",
                "ordering": ("-valid_from",),
                "indexes": [
                    models.Index(
                        fields=["organisation", "valid_from"],
                        name="hospitals_o_organis_1303b3_idx",
                    ),
                    models.Index(
                        fields=["valid_to"], name="hospitals_o_valid_t_1ce3f5_idx"
                    ),
                ],
            },
        ),
    ]
