# Generated by Django 5.2.13 on 2026-04-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0021_isle_of_man"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="website",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
