# Generated by Django 5.2.1 on 2026-08-04 14:30

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0022_organisation_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegratedCareBoardVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valid_from",
                    models.DateField(
                        help_text="The date from which this state of the Integrated Care Board was in force.",
                        verbose_name="Valid from",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="The date on which this state ceased to be in force. NULL means this is the current state.",
                        null=True,
                        verbose_name="Valid to",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=77, null=True
                    ),
                ),
                ("bng_e", models.BigIntegerField(blank=True, default=None, null=True)),
                ("bng_n", models.BigIntegerField(blank=True, default=None, null=True)),
                ("long", models.FloatField(blank=True, default=None, null=True)),
                ("lat", models.FloatField(blank=True, default=None, null=True)),
                (
                    "globalid",
                    models.CharField(
                        blank=True, default=None, max_length=38, null=True
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, default=None, null=True, srid=27700
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "integrated_care_board",
                    models.ForeignKey(
                        help_text="The Integrated Care Board this version is a snapshot of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="hospitals.integratedcareboard",
                        verbose_name="Integrated Care Board",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integrated Care Board version",
                "verbose_name_plural": "Integrated Care Board versions",
                "ordering": ("-valid_from",),
                "indexes": [
                    models.Index(
                        fields=["integrated_care_board", "valid_from"],
                        name="hospitals_i_integra_51cf15_idx",
                    ),
                    models.Index(
                        fields=["valid_to"], name="hospitals_i_valid_t_f074b8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LocalHealthBoardVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valid_from",
                    models.DateField(
                        help_text="The date from which this state of the Local Health Board was in force.",
                        verbose_name="Valid from",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="The date on which this state ceased to be in force. NULL means this is the current state.",
                        null=True,
                        verbose_name="Valid to",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=41, null=True
                    ),
                ),
                (
                    "welsh_name",
                    models.CharField(
                        blank=True, default=None, max_length=40, null=True
                    ),
                ),
                ("bng_e", models.FloatField(blank=True, default=None, null=True)),
                ("bng_n", models.FloatField(blank=True, default=None, null=True)),
                ("long", models.FloatField(blank=True, default=None, null=True)),
                ("lat", models.FloatField(blank=True, default=None, null=True)),
                (
                    "globalid",
                    models.CharField(
                        blank=True, default=None, max_length=38, null=True
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, default=None, null=True, srid=27700
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "local_health_board",
                    models.ForeignKey(
                        help_text="The Local Health Board this version is a snapshot of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="hospitals.localhealthboard",
                        verbose_name="Local Health Board",
                    ),
                ),
            ],
            options={
                "verbose_name": "Local Health Board version",
                "verbose_name_plural": "Local Health Board versions",
                "ordering": ("-valid_from",),
                "indexes": [
                    models.Index(
                        fields=["local_health_board", "valid_from"],
                        name="hospitals_l_local_h_931ecb_idx",
                    ),
                    models.Index(
                        fields=["valid_to"], name="hospitals_l_valid_t_d2b2a4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NHSEnglandRegionVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valid_from",
                    models.DateField(
                        help_text="The date from which this state of the NHS England Region was in force.",
                        verbose_name="Valid from",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="The date on which this state ceased to be in force. NULL means this is the current state.",
                        null=True,
                        verbose_name="Valid to",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=24, null=True
                    ),
                ),
                ("bng_e", models.BigIntegerField(blank=True, default=None, null=True)),
                ("bng_n", models.BigIntegerField(blank=True, default=None, null=True)),
                ("long", models.FloatField(blank=True, default=None, null=True)),
                ("lat", models.FloatField(blank=True, default=None, null=True)),
                (
                    "globalid",
                    models.CharField(
                        blank=True, default=None, max_length=38, null=True
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, default=None, null=True, srid=27700
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "nhs_england_region",
                    models.ForeignKey(
                        help_text="The NHS England Region this version is a snapshot of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="hospitals.nhsenglandregion",
                        verbose_name="NHS England Region",
                    ),
                ),
            ],
            options={
                "verbose_name": "NHS England Region version",
                "verbose_name_plural": "NHS England Region versions",
                "ordering": ("-valid_from",),
                "indexes": [
                    models.Index(
                        fields=["nhs_england_region", "valid_from"],
                        name="hospitals_n_nhs_eng_a30575_idx",
                    ),
                    models.Index(
                        fields=["valid_to"], name="hospitals_n_valid_t_2dfa94_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaediatricDiabetesNetworkVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valid_from",
                    models.DateField(
                        help_text="The date from which this state of the network was in force.",
                        verbose_name="Valid from",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="The date on which this state ceased to be in force. NULL means this is the current state.",
                        null=True,
                        verbose_name="Valid to",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "paediatric_diabetes_network",
                    models.ForeignKey(
                        help_text="The Paediatric Diabetes Network this version is a snapshot of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="hospitals.paediatricdiabetesnetwork",
                        verbose_name="Paediatric Diabetes Network",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paediatric Diabetes Network version",
                "verbose_name_plural": "Paediatric Diabetes Network versions",
                "ordering": ("-valid_from",),
                "indexes": [
                    models.Index(
                        fields=["paediatric_diabetes_network", "valid_from"],
                        name="hospitals_p_paediat_6e8e1c_idx",
                    ),
                    models.Index(
                        fields=["valid_to"], name="hospitals_p_valid_t_f8b072_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaediatricDiabetesUnitVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valid_from",
                    models.DateField(
                        help_text="The date from which this state of the PDU was in force.",
                        verbose_name="Valid from",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="The date on which this state ceased to be in force. NULL means this is the current state.",
                        null=True,
                        verbose_name="Valid to",
                    ),
                ),
                (
                    "unit_name",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "paediatric_diabetes_network_id",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="The network the PDU was associated with at valid_from. For full relationship history use PaediatricDiabetesUnitNetworkMembership.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pdu_versions",
                        to="hospitals.paediatricdiabetesnetwork",
                        verbose_name="Paediatric Diabetes Network (snapshot)",
                    ),
                ),
                (
                    "paediatric_diabetes_unit",
                    models.ForeignKey(
                        help_text="The Paediatric Diabetes Unit this version is a snapshot of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="hospitals.paediatricdiabetesunit",
                        verbose_name="Paediatric Diabetes Unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paediatric Diabetes Unit version",
                "verbose_name_plural": "Paediatric Diabetes Unit versions",
                "ordering": ("-valid_from",),
                "indexes": [
                    models.Index(
                        fields=["paediatric_diabetes_unit", "valid_from"],
                        name="hospitals_p_paediat_4baa6d_idx",
                    ),
                    models.Index(
                        fields=["valid_to"], name="hospitals_p_valid_t_450622_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrustVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valid_from",
                    models.DateField(
                        help_text="The date from which this state of the Trust was in force.",
                        verbose_name="Valid from",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="The date on which this state ceased to be in force. NULL means this is the current state.",
                        null=True,
                        verbose_name="Valid to",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "town",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "postcode",
                    models.CharField(
                        blank=True, default=None, max_length=10, null=True
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "website",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("published_at", models.DateField(blank=True, default=None, null=True)),
                (
                    "trust",
                    models.ForeignKey(
                        help_text="The Trust this version is a snapshot of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="hospitals.trust",
                        verbose_name="Trust",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust version",
                "verbose_name_plural": "Trust versions",
                "ordering": ("-valid_from",),
                "indexes": [
                    models.Index(
                        fields=["trust", "valid_from"],
                        name="hospitals_t_trust_i_5ac2a0_idx",
                    ),
                    models.Index(
                        fields=["valid_to"], name="hospitals_t_valid_t_dab7ed_idx"
                    ),
                ],
            },
        ),
    ]
