# Generated by Django 5.2.1 on 2026-08-04 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0024_baseline_version_backfill"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationIntegratedCareBoardMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valid_from",
                    models.DateField(
                        help_text="The date from which this membership was in force.",
                        verbose_name="Valid from",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="The date on which this membership ceased to be in force. NULL means this is the current membership.",
                        null=True,
                        verbose_name="Valid to",
                    ),
                ),
                (
                    "integrated_care_board",
                    models.ForeignKey(
                        help_text="The ICB the Organisation was a member of over this interval.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organisation_memberships",
                        to="hospitals.integratedcareboard",
                        verbose_name="Integrated Care Board",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        help_text="The Organisation this membership records the parent ICB of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrated_care_board_memberships",
                        to="hospitals.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation–Integrated Care Board membership",
                "verbose_name_plural": "Organisation–Integrated Care Board memberships",
                "ordering": ("-valid_from",),
                "indexes": [
                    models.Index(
                        fields=["organisation", "valid_to"],
                        name="hospitals_o_organis_14cffa_idx",
                    ),
                    models.Index(
                        fields=["integrated_care_board", "valid_from"],
                        name="hospitals_o_integra_300c2a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganisationLocalHealthBoardMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valid_from",
                    models.DateField(
                        help_text="The date from which this membership was in force.",
                        verbose_name="Valid from",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="The date on which this membership ceased to be in force. NULL means this is the current membership.",
                        null=True,
                        verbose_name="Valid to",
                    ),
                ),
                (
                    "local_health_board",
                    models.ForeignKey(
                        help_text="The Local Health Board the Organisation was a member of over this interval.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organisation_memberships",
                        to="hospitals.localhealthboard",
                        verbose_name="Local Health Board",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        help_text="The Organisation this membership records the parent LHB of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="local_health_board_memberships",
                        to="hospitals.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation–Local Health Board membership",
                "verbose_name_plural": "Organisation–Local Health Board memberships",
                "ordering": ("-valid_from",),
                "indexes": [
                    models.Index(
                        fields=["organisation", "valid_to"],
                        name="hospitals_o_organis_6e29ee_idx",
                    ),
                    models.Index(
                        fields=["local_health_board", "valid_from"],
                        name="hospitals_o_local_h_978818_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganisationNHSEnglandRegionMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valid_from",
                    models.DateField(
                        help_text="The date from which this membership was in force.",
                        verbose_name="Valid from",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="The date on which this membership ceased to be in force. NULL means this is the current membership.",
                        null=True,
                        verbose_name="Valid to",
                    ),
                ),
                (
                    "nhs_england_region",
                    models.ForeignKey(
                        help_text="The NHS England Region the Organisation was a member of over this interval.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organisation_memberships",
                        to="hospitals.nhsenglandregion",
                        verbose_name="NHS England Region",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        help_text="The Organisation this membership records the NHS England Region of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nhs_england_region_memberships",
                        to="hospitals.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation–NHS England Region membership",
                "verbose_name_plural": "Organisation–NHS England Region memberships",
                "ordering": ("-valid_from",),
                "indexes": [
                    models.Index(
                        fields=["organisation", "valid_to"],
                        name="hospitals_o_organis_949e76_idx",
                    ),
                    models.Index(
                        fields=["nhs_england_region", "valid_from"],
                        name="hospitals_o_nhs_eng_5d57bc_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganisationOPENUKNetworkMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valid_from",
                    models.DateField(
                        help_text="The date from which this membership was in force.",
                        verbose_name="Valid from",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="The date on which this membership ceased to be in force. NULL means this is the current membership.",
                        null=True,
                        verbose_name="Valid to",
                    ),
                ),
                (
                    "openuk_network",
                    models.ForeignKey(
                        help_text="The OPEN UK Network the Organisation was a member of over this interval.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organisation_memberships",
                        to="hospitals.openuknetwork",
                        verbose_name="OPEN UK Network",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        help_text="The Organisation this membership records the OPEN UK Network of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="openuk_network_memberships",
                        to="hospitals.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation–OPEN UK Network membership",
                "verbose_name_plural": "Organisation–OPEN UK Network memberships",
                "ordering": ("-valid_from",),
                "indexes": [
                    models.Index(
                        fields=["organisation", "valid_to"],
                        name="hospitals_o_organis_a0d3d5_idx",
                    ),
                    models.Index(
                        fields=["openuk_network", "valid_from"],
                        name="hospitals_o_openuk__503578_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganisationPaediatricDiabetesUnitMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valid_from",
                    models.DateField(
                        help_text="The date from which this membership was in force.",
                        verbose_name="Valid from",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="The date on which this membership ceased to be in force. NULL means this is the current membership.",
                        null=True,
                        verbose_name="Valid to",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        help_text="The Organisation this membership records the PDU of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paediatric_diabetes_unit_memberships",
                        to="hospitals.organisation",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "paediatric_diabetes_unit",
                    models.ForeignKey(
                        help_text="The PDU the Organisation was a member of over this interval.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organisation_memberships",
                        to="hospitals.paediatricdiabetesunit",
                        verbose_name="Paediatric Diabetes Unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation–Paediatric Diabetes Unit membership",
                "verbose_name_plural": "Organisation–Paediatric Diabetes Unit memberships",
                "ordering": ("-valid_from",),
                "indexes": [
                    models.Index(
                        fields=["organisation", "valid_to"],
                        name="hospitals_o_organis_1d50d5_idx",
                    ),
                    models.Index(
                        fields=["paediatric_diabetes_unit", "valid_from"],
                        name="hospitals_o_paediat_3592c5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganisationTrustMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valid_from",
                    models.DateField(
                        help_text="The date from which this membership was in force.",
                        verbose_name="Valid from",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="The date on which this membership ceased to be in force. NULL means this is the current membership.",
                        null=True,
                        verbose_name="Valid to",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        help_text="The Organisation this membership records the parent Trust of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trust_memberships",
                        to="hospitals.organisation",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "trust",
                    models.ForeignKey(
                        help_text="The Trust the Organisation was a member of over this interval.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organisation_memberships",
                        to="hospitals.trust",
                        verbose_name="Trust",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation–Trust membership",
                "verbose_name_plural": "Organisation–Trust memberships",
                "ordering": ("-valid_from",),
                "indexes": [
                    models.Index(
                        fields=["organisation", "valid_to"],
                        name="hospitals_o_organis_951dce_idx",
                    ),
                    models.Index(
                        fields=["trust", "valid_from"],
                        name="hospitals_o_trust_i_c743db_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaediatricDiabetesUnitNetworkMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valid_from",
                    models.DateField(
                        help_text="The date from which this membership was in force.",
                        verbose_name="Valid from",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="The date on which this membership ceased to be in force. NULL means this is the current membership.",
                        null=True,
                        verbose_name="Valid to",
                    ),
                ),
                (
                    "paediatric_diabetes_network",
                    models.ForeignKey(
                        help_text="The network the PDU was a member of over this interval.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pdu_memberships",
                        to="hospitals.paediatricdiabetesnetwork",
                        verbose_name="Paediatric Diabetes Network",
                    ),
                ),
                (
                    "paediatric_diabetes_unit",
                    models.ForeignKey(
                        help_text="The PDU this membership records the network of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_memberships",
                        to="hospitals.paediatricdiabetesunit",
                        verbose_name="Paediatric Diabetes Unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paediatric Diabetes Unit–Network membership",
                "verbose_name_plural": "Paediatric Diabetes Unit–Network memberships",
                "ordering": ("-valid_from",),
                "indexes": [
                    models.Index(
                        fields=["paediatric_diabetes_unit", "valid_to"],
                        name="hospitals_p_paediat_16f203_idx",
                    ),
                    models.Index(
                        fields=["paediatric_diabetes_network", "valid_from"],
                        name="hospitals_p_paediat_280dc0_idx",
                    ),
                ],
            },
        ),
    ]
