# Generated by Django 5.2.1 on 2026-08-04 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0025_organisation_parent_memberships"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationLocalAuthorityDistrictMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valid_from",
                    models.DateField(
                        help_text="The date from which this membership was in force.",
                        verbose_name="Valid from",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="The date on which this membership ceased to be in force. NULL means this is the current membership.",
                        null=True,
                        verbose_name="Valid to",
                    ),
                ),
                (
                    "local_authority_district",
                    models.ForeignKey(
                        help_text="The LAD the Organisation was a member of over this interval.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organisation_memberships",
                        to="hospitals.localauthoritydistrict",
                        verbose_name="Local Authority District",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        help_text="The Organisation this membership records the LAD of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="local_authority_district_memberships",
                        to="hospitals.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation–Local Authority District membership",
                "verbose_name_plural": "Organisation–Local Authority District memberships",
                "ordering": ("-valid_from",),
                "indexes": [
                    models.Index(
                        fields=["organisation", "valid_to"],
                        name="hospitals_o_organis_ba73b7_idx",
                    ),
                    models.Index(
                        fields=["local_authority_district", "valid_from"],
                        name="hospitals_o_local_a_2d0926_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganisationLondonBoroughMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valid_from",
                    models.DateField(
                        help_text="The date from which this membership was in force.",
                        verbose_name="Valid from",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="The date on which this membership ceased to be in force. NULL means this is the current membership.",
                        null=True,
                        verbose_name="Valid to",
                    ),
                ),
                (
                    "london_borough",
                    models.ForeignKey(
                        help_text="The London Borough the Organisation was a member of over this interval.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organisation_memberships",
                        to="hospitals.londonborough",
                        verbose_name="London Borough",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        help_text="The Organisation this membership records the London Borough of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="london_borough_memberships",
                        to="hospitals.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation–London Borough membership",
                "verbose_name_plural": "Organisation–London Borough memberships",
                "ordering": ("-valid_from",),
                "indexes": [
                    models.Index(
                        fields=["organisation", "valid_to"],
                        name="hospitals_o_organis_632ae5_idx",
                    ),
                    models.Index(
                        fields=["london_borough", "valid_from"],
                        name="hospitals_o_london__2f53e3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganisationLowerLayerSuperOutputAreaMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valid_from",
                    models.DateField(
                        help_text="The date from which this membership was in force.",
                        verbose_name="Valid from",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="The date on which this membership ceased to be in force. NULL means this is the current membership.",
                        null=True,
                        verbose_name="Valid to",
                    ),
                ),
                (
                    "lower_layer_super_output_area",
                    models.ForeignKey(
                        help_text="The LSOA the Organisation was a member of over this interval.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organisation_memberships",
                        to="hospitals.lowerlayersuperoutputarea",
                        verbose_name="Lower Layer Super Output Area",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        help_text="The Organisation this membership records the LSOA of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lower_layer_super_output_area_memberships",
                        to="hospitals.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation–Lower Layer Super Output Area membership",
                "verbose_name_plural": "Organisation–Lower Layer Super Output Area memberships",
                "ordering": ("-valid_from",),
                "indexes": [
                    models.Index(
                        fields=["organisation", "valid_to"],
                        name="hospitals_o_organis_0fa54b_idx",
                    ),
                    models.Index(
                        fields=["lower_layer_super_output_area", "valid_from"],
                        name="hospitals_o_lower_l_2a88a0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrustIntegratedCareBoardMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valid_from",
                    models.DateField(
                        help_text="The date from which this membership was in force.",
                        verbose_name="Valid from",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="The date on which this membership ceased to be in force. NULL means this is the current membership.",
                        null=True,
                        verbose_name="Valid to",
                    ),
                ),
                (
                    "integrated_care_board",
                    models.ForeignKey(
                        help_text="The ICB the Trust was a member of over this interval.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trust_memberships",
                        to="hospitals.integratedcareboard",
                        verbose_name="Integrated Care Board",
                    ),
                ),
                (
                    "trust",
                    models.ForeignKey(
                        help_text="The Trust this membership records the parent ICB of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrated_care_board_memberships",
                        to="hospitals.trust",
                        verbose_name="Trust",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust–Integrated Care Board membership",
                "verbose_name_plural": "Trust–Integrated Care Board memberships",
                "ordering": ("-valid_from",),
                "indexes": [
                    models.Index(
                        fields=["trust", "valid_to"],
                        name="hospitals_t_trust_i_236f60_idx",
                    ),
                    models.Index(
                        fields=["integrated_care_board", "valid_from"],
                        name="hospitals_t_integra_99daa7_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrustNHSEnglandRegionMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valid_from",
                    models.DateField(
                        help_text="The date from which this membership was in force.",
                        verbose_name="Valid from",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="The date on which this membership ceased to be in force. NULL means this is the current membership.",
                        null=True,
                        verbose_name="Valid to",
                    ),
                ),
                (
                    "nhs_england_region",
                    models.ForeignKey(
                        help_text="The NHS England Region the Trust was a member of over this interval.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trust_memberships",
                        to="hospitals.nhsenglandregion",
                        verbose_name="NHS England Region",
                    ),
                ),
                (
                    "trust",
                    models.ForeignKey(
                        help_text="The Trust this membership records the NHS England Region of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nhs_england_region_memberships",
                        to="hospitals.trust",
                        verbose_name="Trust",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust–NHS England Region membership",
                "verbose_name_plural": "Trust–NHS England Region memberships",
                "ordering": ("-valid_from",),
                "indexes": [
                    models.Index(
                        fields=["trust", "valid_to"],
                        name="hospitals_t_trust_i_fb8fc7_idx",
                    ),
                    models.Index(
                        fields=["nhs_england_region", "valid_from"],
                        name="hospitals_t_nhs_eng_141c8a_idx",
                    ),
                ],
            },
        ),
    ]
