# Generated by Django 5.2.1 on 2026-08-04 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0026_trust_and_boundary_memberships"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaediatricDiabetesUnitSuccession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "succession_date",
                    models.DateField(
                        help_text="The date on which the succession took effect.",
                        verbose_name="Succession date",
                    ),
                ),
                (
                    "succession_type",
                    models.CharField(
                        choices=[
                            ("merger", "Merger"),
                            ("acquisition", "Acquisition"),
                            ("rename", "Rename"),
                            ("closure", "Closure"),
                            ("split", "Split"),
                        ],
                        help_text="The nature of the succession.",
                        max_length=20,
                        verbose_name="Succession type",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional free-text notes about the succession.",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "predecessor",
                    models.ForeignKey(
                        help_text="The PDU that ceased to exist (or was renamed) on the succession date.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="succession_predecessor_links",
                        to="hospitals.paediatricdiabetesunit",
                        verbose_name="Predecessor",
                    ),
                ),
                (
                    "successor",
                    models.ForeignKey(
                        help_text="The PDU that took over from the predecessor on the succession date.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="succession_successor_links",
                        to="hospitals.paediatricdiabetesunit",
                        verbose_name="Successor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paediatric Diabetes Unit succession",
                "verbose_name_plural": "Paediatric Diabetes Unit successions",
                "indexes": [
                    models.Index(
                        fields=["succession_date"],
                        name="hospitals_p_success_6726a8_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TrustSuccession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "succession_date",
                    models.DateField(
                        help_text="The date on which the succession took effect.",
                        verbose_name="Succession date",
                    ),
                ),
                (
                    "succession_type",
                    models.CharField(
                        choices=[
                            ("merger", "Merger"),
                            ("acquisition", "Acquisition"),
                            ("rename", "Rename"),
                            ("closure", "Closure"),
                            ("split", "Split"),
                        ],
                        help_text="The nature of the succession.",
                        max_length=20,
                        verbose_name="Succession type",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional free-text notes about the succession.",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "predecessor",
                    models.ForeignKey(
                        help_text="The Trust that ceased to exist (or was renamed) on the succession date.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="succession_predecessor_links",
                        to="hospitals.trust",
                        verbose_name="Predecessor",
                    ),
                ),
                (
                    "successor",
                    models.ForeignKey(
                        help_text="The Trust that took over from the predecessor on the succession date.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="succession_successor_links",
                        to="hospitals.trust",
                        verbose_name="Successor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust succession",
                "verbose_name_plural": "Trust successions",
                "indexes": [
                    models.Index(
                        fields=["succession_date"],
                        name="hospitals_t_success_88e60b_idx",
                    )
                ],
            },
        ),
    ]
