# Generated by Django 5.2.1 on 2026-08-04 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0027_successions"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationSuccession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "succession_date",
                    models.DateField(
                        help_text="The date on which the succession took effect.",
                        verbose_name="Succession date",
                    ),
                ),
                (
                    "succession_type",
                    models.CharField(
                        choices=[
                            ("merger", "Merger"),
                            ("acquisition", "Acquisition"),
                            ("rename", "Rename"),
                            ("closure", "Closure"),
                            ("split", "Split"),
                            ("code_change", "ODS code change"),
                        ],
                        help_text="The nature of the succession. Use 'ODS code change' when the organisation remains under the same parent trust but its ODS code was reissued.",
                        max_length=20,
                        verbose_name="Succession type",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional free-text notes about the succession.",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "predecessor",
                    models.ForeignKey(
                        help_text="The Organisation that ceased to exist (or was renamed / recoded) on the succession date.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="succession_predecessor_links",
                        to="hospitals.organisation",
                        verbose_name="Predecessor",
                    ),
                ),
                (
                    "successor",
                    models.ForeignKey(
                        help_text="The Organisation that took over from the predecessor on the succession date. This is usually a newly created Organisation row with the new ODS code.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="succession_successor_links",
                        to="hospitals.organisation",
                        verbose_name="Successor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation succession",
                "verbose_name_plural": "Organisation successions",
                "indexes": [
                    models.Index(
                        fields=["succession_date"],
                        name="hospitals_o_success_23b5e6_idx",
                    )
                ],
            },
        ),
    ]
