# Generated by Django 5.2.1 on 2026-08-05 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0028_organisation_succession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationsuccession",
            name="successor",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The Organisation that took over from the predecessor on the succession date. This is usually a newly created Organisation row with the new ODS code. Leave blank for a closure (no successor).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="succession_successor_links",
                to="hospitals.organisation",
                verbose_name="Successor",
            ),
        ),
        migrations.AlterField(
            model_name="paediatricdiabetesunitsuccession",
            name="successor",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The PDU that took over from the predecessor on the succession date. Leave blank for a closure (no successor).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="succession_successor_links",
                to="hospitals.paediatricdiabetesunit",
                verbose_name="Successor",
            ),
        ),
        migrations.AlterField(
            model_name="trustsuccession",
            name="successor",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The Trust that took over from the predecessor on the succession date. Leave blank for a closure (no successor).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="succession_successor_links",
                to="hospitals.trust",
                verbose_name="Successor",
            ),
        ),
    ]
