# Generated by Django 5.2.1 on 2026-08-05

import django.contrib.gis.db.models.fields
from django.db import migrations


def fix_geocode_coordinates_srid(apps, schema_editor):
    """Fix the SRID mismatch on geocode_coordinates.

    The points were always stored as WGS84 lon/lat (the Point() constructor in
    Organisation.save() used srid=4326), but the column was declared srid=27700.
    PostGIS stored the lon/lat values but tagged them with the column's SRID.

    We use ALTER TABLE ... ALTER COLUMN ... TYPE geometry(Point, 4326) USING
    ST_SetSRID(..., 4326) to both retag the stored geometries and change the
    column's registered SRID in one operation. This is the PostGIS-sanctioned
    way to change a geometry column's SRID without transforming the coordinates.

    We use ST_SetSRID (not ST_Transform) because the coordinates are already
    lon/lat — we are changing the SRID tag, not transforming the values.
    """
    schema_editor.execute(
        "ALTER TABLE hospitals_organisation "
        "ALTER COLUMN geocode_coordinates TYPE geometry(Point, 4326) "
        "USING ST_SetSRID(geocode_coordinates::geometry, 4326);"
    )
    schema_editor.execute(
        "ALTER TABLE hospitals_organisationversion "
        "ALTER COLUMN geocode_coordinates TYPE geometry(Point, 4326) "
        "USING ST_SetSRID(geocode_coordinates::geometry, 4326);"
    )


def restore_geocode_coordinates_srid(apps, schema_editor):
    """Reverse: retag back to 27700."""
    schema_editor.execute(
        "ALTER TABLE hospitals_organisation "
        "ALTER COLUMN geocode_coordinates TYPE geometry(Point, 27700) "
        "USING ST_SetSRID(geocode_coordinates::geometry, 27700);"
    )
    schema_editor.execute(
        "ALTER TABLE hospitals_organisationversion "
        "ALTER COLUMN geocode_coordinates TYPE geometry(Point, 27700) "
        "USING ST_SetSRID(geocode_coordinates::geometry, 27700);"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0029_succession_successor_nullable"),
    ]

    operations = [
        # Step 1: change the column SRID and retag the stored geometries in
        # one operation. This avoids the "Geometry SRID does not match column
        # SRID" error that occurs if you try to UPDATE the geometries while
        # the column is still registered as 27700.
        migrations.RunPython(
            fix_geocode_coordinates_srid,
            reverse_code=restore_geocode_coordinates_srid,
        ),
        # Step 2: tell Django the column is now 4326. Django's AlterField will
        # be a no-op on the database (the column is already 4326 from step 1)
        # but updates Django's migration state.
        migrations.AlterField(
            model_name="organisation",
            name="geocode_coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, default=None, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="organisationversion",
            name="geocode_coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, default=None, null=True, srid=4326
            ),
        ),
    ]
