# Generated by Django 5.2.1 on 2026-08-08 13:39

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0032_pdu_lead_organisation_and_name_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="integratedcareboard",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="integratedcareboardversion",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="integratedcareboard",
            name="bng_e",
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="integratedcareboard",
            name="bng_n",
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="integratedcareboard",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, default=None, null=True, srid=27700
            ),
        ),
        migrations.AlterField(
            model_name="integratedcareboard",
            name="globalid",
            field=models.CharField(blank=True, default=None, max_length=38, null=True),
        ),
        migrations.AlterField(
            model_name="integratedcareboard",
            name="lat",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="integratedcareboard",
            name="long",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name="IntegratedCareBoardSuccession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "succession_date",
                    models.DateField(
                        help_text="The date on which the succession took effect.",
                        verbose_name="Succession date",
                    ),
                ),
                (
                    "succession_type",
                    models.CharField(
                        choices=[
                            ("merger", "Merger"),
                            ("acquisition", "Acquisition"),
                            ("rename", "Rename"),
                            ("closure", "Closure"),
                            ("split", "Split"),
                        ],
                        help_text="The nature of the succession.",
                        max_length=20,
                        verbose_name="Succession type",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional free-text notes about the succession.",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "predecessor",
                    models.ForeignKey(
                        help_text="The Integrated Care Board that ceased to exist (or was renamed) on the succession date.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="succession_predecessor_links",
                        to="hospitals.integratedcareboard",
                        verbose_name="Predecessor",
                    ),
                ),
                (
                    "successor",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="The Integrated Care Board that took over from the predecessor on the succession date. Leave blank for a closure (no successor).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="succession_successor_links",
                        to="hospitals.integratedcareboard",
                        verbose_name="Successor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integrated Care Board succession",
                "verbose_name_plural": "Integrated Care Board successions",
                "indexes": [
                    models.Index(
                        fields=["succession_date"],
                        name="hospitals_i_success_29d3e6_idx",
                    )
                ],
            },
        ),
    ]
