# Generated by Django 5.2.1 on 2026-08-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0033_integratedcareboard_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="organisationversion",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
