NORTHERN_IRELAND_POSTCODES = [
    "BT30 9QG",
    "BT71 5HG",
    "BT5 4QA",
    "BT67 0UQ",
    "BT74 7NF",
    "BT28 3PP",
    "BT2 7DX",
    "BT41 1QZ",
    "BT28 2NT",
    "BT35 6BP",
    "BT20 3QW",
    "BT66 6HZ",
    "BT47 4DU",
    "BT62 3LR",
    "BT34 4GG",
    "BT62 4DX",
]

NORTHERN_IRELAND_ADDRESSES = [
    {
        "query": "BT30 9QG",
        "result": {
            "postcode": "BT30 9QG",
            "quality": 1,
            "eastings": 352684,
            "northings": 352769,
            "country": "Northern Ireland",
            "nhs_ha": "Health & Social Care Board",
            "longitude": -5.649627,
            "latitude": 54.400614,
            "european_electoral_region": "Northern Ireland",
            "primary_care_trust": "South Eastern",
            "region": None,
            "lsoa": "Killyleagh",
            "msoa": None,
            "incode": "9QG",
            "outcode": "BT30",
            "parliamentary_constituency": "Strangford",
            "admin_district": "Newry, Mourne and Down",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "198412",
            "admin_ward": "Crossgar and Killyleagh",
            "ced": None,
            "ccg": "South Eastern",
            "nuts": "Newry, Mourne and Down",
            "pfa": "(pseudo) Northern Ireland",
            "codes": {
                "admin_district": "N09000010",
                "admin_county": "N99999999",
                "admin_ward": "N08001013",
                "parish": "N99999999",
                "parliamentary_constituency": "N06000016",
                "ccg": "ZC040",
                "ccg_id": "ZC040",
                "ced": "N99999999",
                "nuts": "TLN08",
                "lsoa": "95NN15W1",
                "msoa": "N99999999",
                "lau2": "N09000010",
                "pfa": "N99999999",
            },
        },
    },
    {
        "query": "BT71 5HG",
        "result": {
            "postcode": "BT71 5HG",
            "quality": 1,
            "eastings": 291630,
            "northings": 372187,
            "country": "Northern Ireland",
            "nhs_ha": "Health & Social Care Board",
            "longitude": -6.58333,
            "latitude": 54.589636,
            "european_electoral_region": "Northern Ireland",
            "primary_care_trust": "Northern",
            "region": None,
            "lsoa": "Killycolpy",
            "msoa": None,
            "incode": "5HG",
            "outcode": "BT71",
            "parliamentary_constituency": "Mid Ulster",
            "admin_district": "Mid Ulster",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "198412",
            "admin_ward": "Ardboe",
            "ced": None,
            "ccg": "Northern",
            "nuts": "Mid Ulster",
            "pfa": "(pseudo) Northern Ireland",
            "codes": {
                "admin_district": "N09000009",
                "admin_county": "N99999999",
                "admin_ward": "N08000901",
                "parish": "N99999999",
                "parliamentary_constituency": "N06000010",
                "ccg": "ZC020",
                "ccg_id": "ZC020",
                "ced": "N99999999",
                "nuts": "TLN11",
                "lsoa": "95KK05W1",
                "msoa": "N99999999",
                "lau2": "N09000009",
                "pfa": "N99999999",
            },
        },
    },
    {
        "query": "BT5 4QA",
        "result": {
            "postcode": "BT5 4QA",
            "quality": 1,
            "eastings": 336044,
            "northings": 374018,
            "country": "Northern Ireland",
            "nhs_ha": "Health & Social Care Board",
            "longitude": -5.895876,
            "latitude": 54.596085,
            "european_electoral_region": "Northern Ireland",
            "primary_care_trust": "Belfast",
            "region": None,
            "lsoa": "The Mount 1",
            "msoa": None,
            "incode": "4QA",
            "outcode": "BT5",
            "parliamentary_constituency": "Belfast East",
            "admin_district": "Belfast",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "200211",
            "admin_ward": "Beersbridge",
            "ced": None,
            "ccg": "Belfast",
            "nuts": "Belfast",
            "pfa": "(pseudo) Northern Ireland",
            "codes": {
                "admin_district": "N09000003",
                "admin_county": "N99999999",
                "admin_ward": "N08000308",
                "parish": "N99999999",
                "parliamentary_constituency": "N06000001",
                "ccg": "ZC010",
                "ccg_id": "ZC010",
                "ced": "N99999999",
                "nuts": "TLN06",
                "lsoa": "95GG44S1",
                "msoa": "N99999999",
                "lau2": "N09000003",
                "pfa": "N99999999",
            },
        },
    },
    {
        "query": "BT67 0UQ",
        "result": {
            "postcode": "BT67 0UQ",
            "quality": 1,
            "eastings": 317503,
            "northings": 363555,
            "country": "Northern Ireland",
            "nhs_ha": "Health & Social Care Board",
            "longitude": -6.186743,
            "latitude": 54.506787,
            "european_electoral_region": "Northern Ireland",
            "primary_care_trust": "South Eastern",
            "region": None,
            "lsoa": "Maghaberry 2",
            "msoa": None,
            "incode": "0UQ",
            "outcode": "BT67",
            "parliamentary_constituency": "Lagan Valley",
            "admin_district": "Lisburn and Castlereagh",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "200609",
            "admin_ward": "Maghaberry",
            "ced": None,
            "ccg": "South Eastern",
            "nuts": "Lisburn and Castlereagh",
            "pfa": "(pseudo) Northern Ireland",
            "codes": {
                "admin_district": "N09000007",
                "admin_county": "N99999999",
                "admin_ward": "N08000730",
                "parish": "N99999999",
                "parliamentary_constituency": "N06000009",
                "ccg": "ZC040",
                "ccg_id": "ZC040",
                "ced": "N99999999",
                "nuts": "TLN14",
                "lsoa": "95SS21S2",
                "msoa": "N99999999",
                "lau2": "N09000007",
                "pfa": "N99999999",
            },
        },
    },
    {
        "query": "BT74 7NF",
        "result": {
            "postcode": "BT74 7NF",
            "quality": 1,
            "eastings": 222004,
            "northings": 344438,
            "country": "Northern Ireland",
            "nhs_ha": "Health & Social Care Board",
            "longitude": -7.662377,
            "latitude": 54.34818,
            "european_electoral_region": "Northern Ireland",
            "primary_care_trust": "Western",
            "region": None,
            "lsoa": "Portora",
            "msoa": None,
            "incode": "7NF",
            "outcode": "BT74",
            "parliamentary_constituency": "Fermanagh and South Tyrone",
            "admin_district": "Fermanagh and Omagh",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "199501",
            "admin_ward": "Portora",
            "ced": None,
            "ccg": "Western",
            "nuts": "Fermanagh and Omagh",
            "pfa": "(pseudo) Northern Ireland",
            "codes": {
                "admin_district": "N09000006",
                "admin_county": "N99999999",
                "admin_ward": "N08000633",
                "parish": "N99999999",
                "parliamentary_constituency": "N06000007",
                "ccg": "ZC050",
                "ccg_id": "ZC050",
                "ced": "N99999999",
                "nuts": "TLN16",
                "lsoa": "95PP20W1",
                "msoa": "N99999999",
                "lau2": "N09000006",
                "pfa": "N99999999",
            },
        },
    },
    {
        "query": "BT28 3PP",
        "result": {
            "postcode": "BT28 3PP",
            "quality": 1,
            "eastings": 326919,
            "northings": 365669,
            "country": "Northern Ireland",
            "nhs_ha": "Health & Social Care Board",
            "longitude": -6.040562,
            "latitude": 54.5235,
            "european_electoral_region": "Northern Ireland",
            "primary_care_trust": "South Eastern",
            "region": None,
            "lsoa": "Wallace Park 2",
            "msoa": None,
            "incode": "3PP",
            "outcode": "BT28",
            "parliamentary_constituency": "Lagan Valley",
            "admin_district": "Lisburn and Castlereagh",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "198412",
            "admin_ward": "Harmony Hill",
            "ced": None,
            "ccg": "South Eastern",
            "nuts": "Lisburn and Castlereagh",
            "pfa": "(pseudo) Northern Ireland",
            "codes": {
                "admin_district": "N09000007",
                "admin_county": "N99999999",
                "admin_ward": "N08000720",
                "parish": "N99999999",
                "parliamentary_constituency": "N06000009",
                "ccg": "ZC040",
                "ccg_id": "ZC040",
                "ced": "N99999999",
                "nuts": "TLN14",
                "lsoa": "95SS30S2",
                "msoa": "N99999999",
                "lau2": "N09000007",
                "pfa": "N99999999",
            },
        },
    },
    {
        "query": "BT2 7DX",
        "result": {
            "postcode": "BT2 7DX",
            "quality": 1,
            "eastings": 333784,
            "northings": 373855,
            "country": "Northern Ireland",
            "nhs_ha": "Health & Social Care Board",
            "longitude": -5.930891,
            "latitude": 54.595224,
            "european_electoral_region": "Northern Ireland",
            "primary_care_trust": "Belfast",
            "region": None,
            "lsoa": "Shaftesbury 1",
            "msoa": None,
            "incode": "7DX",
            "outcode": "BT2",
            "parliamentary_constituency": "Belfast South",
            "admin_district": "Belfast",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "198412",
            "admin_ward": "Central",
            "ced": None,
            "ccg": "Belfast",
            "nuts": "Belfast",
            "pfa": "(pseudo) Northern Ireland",
            "codes": {
                "admin_district": "N09000003",
                "admin_county": "N99999999",
                "admin_ward": "N08000315",
                "parish": "N99999999",
                "parliamentary_constituency": "N06000003",
                "ccg": "ZC010",
                "ccg_id": "ZC010",
                "ced": "N99999999",
                "nuts": "TLN06",
                "lsoa": "95GG39S1",
                "msoa": "N99999999",
                "lau2": "N09000003",
                "pfa": "N99999999",
            },
        },
    },
    {
        "query": "BT41 1QZ",
        "result": {
            "postcode": "BT41 1QZ",
            "quality": 1,
            "eastings": 314830,
            "northings": 388110,
            "country": "Northern Ireland",
            "nhs_ha": "Health & Social Care Board",
            "longitude": -6.218376,
            "latitude": 54.727872,
            "european_electoral_region": "Northern Ireland",
            "primary_care_trust": "Northern",
            "region": None,
            "lsoa": "Springfarm 1",
            "msoa": None,
            "incode": "1QZ",
            "outcode": "BT41",
            "parliamentary_constituency": "South Antrim",
            "admin_district": "Antrim and Newtownabbey",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "198412",
            "admin_ward": "Springfarm",
            "ced": None,
            "ccg": "Northern",
            "nuts": "Antrim and Newtownabbey",
            "pfa": "(pseudo) Northern Ireland",
            "codes": {
                "admin_district": "N09000001",
                "admin_county": "N99999999",
                "admin_ward": "N08000134",
                "parish": "N99999999",
                "parliamentary_constituency": "N06000014",
                "ccg": "ZC020",
                "ccg_id": "ZC020",
                "ced": "N99999999",
                "nuts": "TLN13",
                "lsoa": "95AA15S1",
                "msoa": "N99999999",
                "lau2": "N09000001",
                "pfa": "N99999999",
            },
        },
    },
    {
        "query": "BT28 2NT",
        "result": {
            "postcode": "BT28 2NT",
            "quality": 1,
            "eastings": 320308,
            "northings": 366957,
            "country": "Northern Ireland",
            "nhs_ha": "Health & Social Care Board",
            "longitude": -6.142078,
            "latitude": 54.536675,
            "european_electoral_region": "Northern Ireland",
            "primary_care_trust": "South Eastern",
            "region": None,
            "lsoa": "Ballinderry 1",
            "msoa": None,
            "incode": "2NT",
            "outcode": "BT28",
            "parliamentary_constituency": "Lagan Valley",
            "admin_district": "Lisburn and Castlereagh",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "198412",
            "admin_ward": "Stonyford",
            "ced": None,
            "ccg": "South Eastern",
            "nuts": "Lisburn and Castlereagh",
            "pfa": "(pseudo) Northern Ireland",
            "codes": {
                "admin_district": "N09000007",
                "admin_county": "N99999999",
                "admin_ward": "N08000738",
                "parish": "N99999999",
                "parliamentary_constituency": "N06000009",
                "ccg": "ZC040",
                "ccg_id": "ZC040",
                "ced": "N99999999",
                "nuts": "TLN14",
                "lsoa": "95SS01S1",
                "msoa": "N99999999",
                "lau2": "N09000007",
                "pfa": "N99999999",
            },
        },
    },
    {
        "query": "BT35 6BP",
        "result": {
            "postcode": "BT35 6BP",
            "quality": 1,
            "eastings": 308628,
            "northings": 327053,
            "country": "Northern Ireland",
            "nhs_ha": "Health & Social Care Board",
            "longitude": -6.336978,
            "latitude": 54.180988,
            "european_electoral_region": "Northern Ireland",
            "primary_care_trust": "Southern",
            "region": None,
            "lsoa": "Drumgullion 1",
            "msoa": None,
            "incode": "6BP",
            "outcode": "BT35",
            "parliamentary_constituency": "Newry and Armagh",
            "admin_district": "Newry, Mourne and Down",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "198412",
            "admin_ward": "Damolly",
            "ced": None,
            "ccg": "Southern",
            "nuts": "Newry, Mourne and Down",
            "pfa": "(pseudo) Northern Ireland",
            "codes": {
                "admin_district": "N09000010",
                "admin_county": "N99999999",
                "admin_ward": "N08001015",
                "parish": "N99999999",
                "parliamentary_constituency": "N06000011",
                "ccg": "ZC030",
                "ccg_id": "ZC030",
                "ced": "N99999999",
                "nuts": "TLN08",
                "lsoa": "95VV15S1",
                "msoa": "N99999999",
                "lau2": "N09000010",
                "pfa": "N99999999",
            },
        },
    },
    {
        "query": "BT20 3QW",
        "result": {
            "postcode": "BT20 3QW",
            "quality": 1,
            "eastings": 349159,
            "northings": 382026,
            "country": "Northern Ireland",
            "nhs_ha": "Health & Social Care Board",
            "longitude": -5.689061,
            "latitude": 54.664267,
            "european_electoral_region": "Northern Ireland",
            "primary_care_trust": "South Eastern",
            "region": None,
            "lsoa": "Princetown",
            "msoa": None,
            "incode": "3QW",
            "outcode": "BT20",
            "parliamentary_constituency": "North Down",
            "admin_district": "Ards and North Down",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "198607",
            "admin_ward": "Bryansburn",
            "ced": None,
            "ccg": "South Eastern",
            "nuts": "Ards and North Down",
            "pfa": "(pseudo) Northern Ireland",
            "codes": {
                "admin_district": "N09000011",
                "admin_county": "N99999999",
                "admin_ward": "N08001109",
                "parish": "N99999999",
                "parliamentary_constituency": "N06000013",
                "ccg": "ZC040",
                "ccg_id": "ZC040",
                "ced": "N99999999",
                "nuts": "TLN09",
                "lsoa": "95XX21W1",
                "msoa": "N99999999",
                "lau2": "N09000011",
                "pfa": "N99999999",
            },
        },
    },
    {
        "query": "BT66 6HZ",
        "result": {
            "postcode": "BT66 6HZ",
            "quality": 1,
            "eastings": 307813,
            "northings": 359515,
            "country": "Northern Ireland",
            "nhs_ha": "Health & Social Care Board",
            "longitude": -6.337737,
            "latitude": 54.472661,
            "european_electoral_region": "Northern Ireland",
            "primary_care_trust": "Southern",
            "region": None,
            "lsoa": "Woodville 2",
            "msoa": None,
            "incode": "6HZ",
            "outcode": "BT66",
            "parliamentary_constituency": "Upper Bann",
            "admin_district": "Armagh City, Banbridge and Craigavon",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "199007",
            "admin_ward": "Lough Road",
            "ced": None,
            "ccg": "Southern",
            "nuts": "Armagh City, Banbridge and Craigavon",
            "pfa": "(pseudo) Northern Ireland",
            "codes": {
                "admin_district": "N09000002",
                "admin_county": "N99999999",
                "admin_ward": "N08000224",
                "parish": "N99999999",
                "parliamentary_constituency": "N06000017",
                "ccg": "ZC030",
                "ccg_id": "ZC030",
                "ced": "N99999999",
                "nuts": "TLN07",
                "lsoa": "95LL26S2",
                "msoa": "N99999999",
                "lau2": "N09000002",
                "pfa": "N99999999",
            },
        },
    },
    {
        "query": "BT47 4DU",
        "result": {
            "postcode": "BT47 4DU",
            "quality": 1,
            "eastings": 254051,
            "northings": 407750,
            "country": "Northern Ireland",
            "nhs_ha": "Health & Social Care Board",
            "longitude": -7.157938,
            "latitude": 54.914469,
            "european_electoral_region": "Northern Ireland",
            "primary_care_trust": "Western",
            "region": None,
            "lsoa": "Claudy 1",
            "msoa": None,
            "incode": "4DU",
            "outcode": "BT47",
            "parliamentary_constituency": "East Londonderry",
            "admin_district": "Derry City and Strabane",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "199806",
            "admin_ward": "Claudy",
            "ced": None,
            "ccg": "Western",
            "nuts": "Derry City and Strabane",
            "pfa": "(pseudo) Northern Ireland",
            "codes": {
                "admin_district": "N09000005",
                "admin_county": "N99999999",
                "admin_ward": "N08000509",
                "parish": "N99999999",
                "parliamentary_constituency": "N06000006",
                "ccg": "ZC050",
                "ccg_id": "ZC050",
                "ced": "N99999999",
                "nuts": "TLN10",
                "lsoa": "95MM09S1",
                "msoa": "N99999999",
                "lau2": "N09000005",
                "pfa": "N99999999",
            },
        },
    },
    {
        "query": "BT62 3LR",
        "result": {
            "postcode": "BT62 3LR",
            "quality": 1,
            "eastings": 300087,
            "northings": 351976,
            "country": "Northern Ireland",
            "nhs_ha": "Health & Social Care Board",
            "longitude": -6.459404,
            "latitude": 54.40654,
            "european_electoral_region": "Northern Ireland",
            "primary_care_trust": "Southern",
            "region": None,
            "lsoa": "Brownstown 1",
            "msoa": None,
            "incode": "3LR",
            "outcode": "BT62",
            "parliamentary_constituency": "Upper Bann",
            "admin_district": "Armagh City, Banbridge and Craigavon",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "199002",
            "admin_ward": "Mahon",
            "ced": None,
            "ccg": "Southern",
            "nuts": "Armagh City, Banbridge and Craigavon",
            "pfa": "(pseudo) Northern Ireland",
            "codes": {
                "admin_district": "N09000002",
                "admin_county": "N99999999",
                "admin_ward": "N08000228",
                "parish": "N99999999",
                "parliamentary_constituency": "N06000017",
                "ccg": "ZC030",
                "ccg_id": "ZC030",
                "ced": "N99999999",
                "nuts": "TLN07",
                "lsoa": "95LL06S1",
                "msoa": "N99999999",
                "lau2": "N09000002",
                "pfa": "N99999999",
            },
        },
    },
    {
        "query": "BT34 4GG",
        "result": {
            "postcode": "BT34 4GG",
            "quality": 1,
            "eastings": 330728,
            "northings": 314235,
            "country": "Northern Ireland",
            "nhs_ha": "Health & Social Care Board",
            "longitude": -6.004239,
            "latitude": 54.060755,
            "european_electoral_region": "Northern Ireland",
            "primary_care_trust": "Southern",
            "region": None,
            "lsoa": "Kilkeel Central 1",
            "msoa": None,
            "incode": "4GG",
            "outcode": "BT34",
            "parliamentary_constituency": "South Down",
            "admin_district": "Newry, Mourne and Down",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "201103",
            "admin_ward": "Kilkeel",
            "ced": None,
            "ccg": "Southern",
            "nuts": "Newry, Mourne and Down",
            "pfa": "(pseudo) Northern Ireland",
            "codes": {
                "admin_district": "N09000010",
                "admin_county": "N99999999",
                "admin_ward": "N08001025",
                "parish": "N99999999",
                "parliamentary_constituency": "N06000015",
                "ccg": "ZC030",
                "ccg_id": "ZC030",
                "ced": "N99999999",
                "nuts": "TLN08",
                "lsoa": "95VV18S1",
                "msoa": "N99999999",
                "lau2": "N09000010",
                "pfa": "N99999999",
            },
        },
    },
    {
        "query": "BT62 4DX",
        "result": {
            "postcode": "BT62 4DX",
            "quality": 1,
            "eastings": 299837,
            "northings": 353632,
            "country": "Northern Ireland",
            "nhs_ha": "Health & Social Care Board",
            "longitude": -6.462696,
            "latitude": 54.42146,
            "european_electoral_region": "Northern Ireland",
            "primary_care_trust": "Southern",
            "region": None,
            "lsoa": "Ballybay",
            "msoa": None,
            "incode": "4DX",
            "outcode": "BT62",
            "parliamentary_constituency": "Upper Bann",
            "admin_district": "Armagh City, Banbridge and Craigavon",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "198412",
            "admin_ward": "Ballybay",
            "ced": None,
            "ccg": "Southern",
            "nuts": "Armagh City, Banbridge and Craigavon",
            "pfa": "(pseudo) Northern Ireland",
            "codes": {
                "admin_district": "N09000002",
                "admin_county": "N99999999",
                "admin_ward": "N08000202",
                "parish": "N99999999",
                "parliamentary_constituency": "N06000017",
                "ccg": "ZC030",
                "ccg_id": "ZC030",
                "ced": "N99999999",
                "nuts": "TLN07",
                "lsoa": "95LL03W1",
                "msoa": "N99999999",
                "lau2": "N09000002",
                "pfa": "N99999999",
            },
        },
    },
]
