PZ_CODES = [
    {"ods_code": "RM102", "npda_code": "PZ002"},
    {"ods_code": "RXF05", "npda_code": "PZ003"},
    {"ods_code": "RNS01", "npda_code": "PZ004"},
    {"ods_code": "RTGFG", "npda_code": "PZ005"},
    {"ods_code": "RP5DR", "npda_code": "PZ006"},
    {"ods_code": "RTH08", "npda_code": "PZ007"},
    {"ods_code": "RJN71", "npda_code": "PZ009"},
    {"ods_code": "RC971", "npda_code": "PZ010"},
    {"ods_code": "RAL26", "npda_code": "PZ012"},
    {"ods_code": "RALC7", "npda_code": "PZ014"},
    {
        "ods_code": "RM325",
        "npda_code": "PZ015",
    },  # WYTHENSHAWE HOSPITAL (RM325 - parent MANCHESTER UNIVERSITY NHS FOUNDATION TRUST - RA0): this is the correct affiliation
    #  Note that it  has two ODS codes on the spine: the other is R0A07, parent Northern Care Alliance. This is incorrect. Note that Wythenshawe Hospital has a PZ code of PZ015,
    # which is different to the parent organisation ROA (whose children have PZ codes of PZ136)
    {"ods_code": "RP5BA", "npda_code": "PZ016"},
    {"ods_code": "RBD01", "npda_code": "PZ017"},
    {"ods_code": "RYR18", "npda_code": "PZ018"},
    {"ods_code": "RAJ12", "npda_code": "PZ019"},  # basildon formerly RDDH0
    {"ods_code": "RJL30", "npda_code": "PZ020"},
    {"ods_code": "RDU50", "npda_code": "PZ021"},
    {"ods_code": "RNNBX", "npda_code": "PZ022"},
    {"ods_code": "RJ701", "npda_code": "PZ023"},
    {"ods_code": "RVV", "npda_code": "PZ024"},
    {"ods_code": "RWA01", "npda_code": "PZ026"},
    {"ods_code": "RTR45", "npda_code": "PZ027"},
    {"ods_code": "RXQ02", "npda_code": "PZ028"},
    {"ods_code": "RBT20", "npda_code": "PZ030"},
    {"ods_code": "RYR16", "npda_code": "PZ031"},
    {"ods_code": "RTD02", "npda_code": "PZ032"},
    {"ods_code": "RTG02", "npda_code": "PZ033"},
    {"ods_code": "RN541", "npda_code": "PZ034"},
    {"ods_code": "RHW01", "npda_code": "PZ035"},
    {"ods_code": "R1HKH", "npda_code": "PZ036"},
    {"ods_code": "RXQ50", "npda_code": "PZ038"},
    {"ods_code": "RRK97", "npda_code": "PZ040"},
    {"ods_code": "RGT01", "npda_code": "PZ041"},
    {"ods_code": "RX1RA", "npda_code": "PZ042"},
    {"ods_code": "RKEQ4", "npda_code": "PZ045"},
    {"ods_code": "RCF22", "npda_code": "PZ047"},
    {"ods_code": "RWDDA", "npda_code": "PZ048"},
    {"ods_code": "RWWWH", "npda_code": "PZ049"},
    {"ods_code": "RVR", "npda_code": "PZ050"},
    {"ods_code": "RJL32", "npda_code": "PZ053"},
    {"ods_code": "R0D01", "npda_code": "PZ054"},  # Poole Hospital formerly RD300
    {"ods_code": "RWEAA", "npda_code": "PZ055"},
    {"ods_code": "RAX01", "npda_code": "PZ057"},
    {"ods_code": "R1HNH", "npda_code": "PZ058"},
    {"ods_code": "R1H12", "npda_code": "PZ059"},
    {"ods_code": "RH801", "npda_code": "PZ060"},
    {"ods_code": "RJ611", "npda_code": "PZ062"},
    {"ods_code": "RFSDA", "npda_code": "PZ064"},
    {"ods_code": "RJE09", "npda_code": "PZ065"},
    {"ods_code": "REF12", "npda_code": "PZ067"},
    {"ods_code": "RD130", "npda_code": "PZ068"},
    {"ods_code": "RWJ09", "npda_code": "PZ069"},
    {"ods_code": "RGR50", "npda_code": "PZ072"},
    {"ods_code": "RWP01", "npda_code": "PZ073"},
    {"ods_code": "RBS25", "npda_code": "PZ074"},
    {"ods_code": "R1F01", "npda_code": "PZ075"},
    {"ods_code": "RDEE4", "npda_code": "PZ076"},
    {"ods_code": "RJE01", "npda_code": "PZ078"},
    {"ods_code": "R0B01", "npda_code": "PZ080"},
    {"ods_code": "RJ122", "npda_code": "PZ082"},
    {"ods_code": "RWP31", "npda_code": "PZ084"},
    {"ods_code": "RJZ30", "npda_code": "PZ085"},
    {"ods_code": "RGN90", "npda_code": "PZ086"},
    {"ods_code": "RA201", "npda_code": "PZ088"},
    {"ods_code": "R1K01", "npda_code": "PZ089"},
    {"ods_code": "RXR20", "npda_code": "PZ091"},
    {"ods_code": "RXWAT", "npda_code": "PZ094"},
    {"ods_code": "RK950", "npda_code": "PZ096"},
    {"ods_code": "RXK02", "npda_code": "PZ097"},
    {"ods_code": "RWH", "npda_code": "PZ099"},
    {
        "ods_code": "RH880",
        "npda_code": "PZ100",
    },  # North Devon formerly RBZ12 til 1/3/22
    {"ods_code": "RR801", "npda_code": "PZ101"},
    {"ods_code": "RAS01", "npda_code": "PZ102"},
    {"ods_code": "RRF02", "npda_code": "PZ104"},
    {"ods_code": "RAE05", "npda_code": "PZ105"},
    {"ods_code": "RXL01", "npda_code": "PZ106"},
    {"ods_code": "RR7EN", "npda_code": "PZ107"},
    {"ods_code": "RQ301", "npda_code": "PZ108"},
    {"ods_code": "RHM01", "npda_code": "PZ109"},
    {"ods_code": "RVY02", "npda_code": "PZ110"},
    {"ods_code": "RLQ01", "npda_code": "PZ111"},
    {"ods_code": "RCBCA", "npda_code": "PZ112"},
    {"ods_code": "RCB55", "npda_code": "PZ114"},
    {"ods_code": "RJ224", "npda_code": "PZ118"},
    {"ods_code": "RN707", "npda_code": "PZ119"},
    {"ods_code": "RTFFS", "npda_code": "PZ120"},
    {"ods_code": "RLT09", "npda_code": "PZ121"},
    {"ods_code": "RKB01", "npda_code": "PZ122"},
    {"ods_code": "RWF03", "npda_code": "PZ125"},
    {"ods_code": "RPA02", "npda_code": "PZ126"},
    {"ods_code": "RGP75", "npda_code": "PZ127"},
    {"ods_code": "RWDLA", "npda_code": "PZ128"},
    {"ods_code": "RCD01", "npda_code": "PZ129"},
    {"ods_code": "RQM01", "npda_code": "PZ130"},
    {"ods_code": "RGN80", "npda_code": "PZ131"},
    {"ods_code": "RTRAT", "npda_code": "PZ133"},
    {"ods_code": "G0W1C", "npda_code": "PZ135"},  # Royal Alexandra
    {
        "ods_code": "R0A",
        "npda_code": "PZ136",
    },  # MANCHESTER UNIVERSITY NHS FOUNDATION TRUST is R0A.
    #  It's child organisations include MANCHESTER LOCAL CARE ORGANISATION (COX3P), NORTH MANCHESTER GENERAL HOSPITAL (R0A66),
    #  ROYAL MANCHESTER CHILDREN'S HOSPITAL (R0A03), TRAFFORD LOCAL CARE ORGANISATION (Q3K9W), WYTHENSHAWE HOSPITAL (RM325)
    # Note that Wythenshawe Hospital has a PZ code of PZ015, which is different to the parent organisation
    {
        "ods_code": "RH5A8",
        "npda_code": "PZ137",
    },  # Musgrove park formerly RBA11 til 31/3/2020
    {"ods_code": "RJC02", "npda_code": "PZ138"},
    {"ods_code": "RA723", "npda_code": "PZ139"},
    {"ods_code": "RMP01", "npda_code": "PZ140"},
    {"ods_code": "R0B0Q", "npda_code": "PZ141"},
    {"ods_code": "RRK98", "npda_code": "PZ144"},
    {"ods_code": "RD816", "npda_code": "PZ145"},
    {"ods_code": "RAJ01", "npda_code": "PZ146"},
    {"ods_code": "RFFAA", "npda_code": "PZ149"},
    {"ods_code": "RNN62", "npda_code": "PZ150"},
    {"ods_code": "RJ231", "npda_code": "PZ151"},
    {"ods_code": "RA901", "npda_code": "PZ152"},
    {"ods_code": "RBN01", "npda_code": "PZ153"},
    {"ods_code": "RCX70", "npda_code": "PZ156"},
    {"ods_code": "RAL01", "npda_code": "PZ157"},
    {"ods_code": "RN506", "npda_code": "PZ159"},
    {"ods_code": "RXPBA", "npda_code": "PZ160"},
    {"ods_code": "RXPDA", "npda_code": "PZ161"},
    {"ods_code": "RXPCP", "npda_code": "PZ162"},
    {"ods_code": "RVWAE", "npda_code": "PZ163"},
    {"ods_code": "RFRPA", "npda_code": "PZ164"},
    {"ods_code": "RTX", "npda_code": "PZ167"},
    {"ods_code": "RWDLP", "npda_code": "PZ168"},
    {"ods_code": "RNZ02", "npda_code": "PZ169"},
    {"ods_code": "RBL14", "npda_code": "PZ170"},
    {
        "ods_code": "R1LCT",
        "npda_code": "PZ171",
    },  # broomfield formerly RQ8L0 to 31/3/2020
    {"ods_code": "RWG02", "npda_code": "PZ172"},
    {"ods_code": "RA430", "npda_code": "PZ173"},
    {"ods_code": "RNQ51", "npda_code": "PZ174"},
    {"ods_code": "RTK01", "npda_code": "PZ176"},
    {"ods_code": "RMC01", "npda_code": "PZ177"},
    {"ods_code": "RBK02", "npda_code": "PZ178"},
    {"ods_code": "RJR", "npda_code": "PZ179"},
    {"ods_code": "RK5BC", "npda_code": "PZ180"},
    {"ods_code": "RDE03", "npda_code": "PZ181"},
    {"ods_code": "RQM91", "npda_code": "PZ182"},
    {"ods_code": "RXN02", "npda_code": "PZ183"},
    {"ods_code": "RWY", "npda_code": "PZ186"},
    {"ods_code": "R1K04", "npda_code": "PZ191"},
    {"ods_code": "RP401", "npda_code": "PZ196"},
    {"ods_code": "RAPNM", "npda_code": "PZ199"},
    {"ods_code": "RQWG0", "npda_code": "PZ200"},
    {"ods_code": "RYJ01", "npda_code": "PZ202"},
    {"ods_code": "RRV03", "npda_code": "PZ203"},
    {
        "ods_code": "RM3",
        "npda_code": "PZ206",
    },  # Pennine Acute Hospitals NHS Trust was RW6 and merged with Salford Royal NHS Foundation Trust, RM3 - currently not in use
    {"ods_code": "RTP04", "npda_code": "PZ213"},
    {"ods_code": "RJZ01", "npda_code": "PZ215"},
    {"ods_code": "RWFTW", "npda_code": "PZ216"},
    {"ods_code": "RDU01", "npda_code": "PZ218"},
    {"ods_code": "RCUEF", "npda_code": "PZ219"},
    {"ods_code": "RC979", "npda_code": "PZ220"},  # Bedford Hospital
    {"ods_code": "RGT2X", "npda_code": "PZ010"},  # Luton and Dunstable Hospital
    {"ods_code": "RN325", "npda_code": "PZ221"},
    {"ods_code": "RL403", "npda_code": "PZ222"},
    {"ods_code": "RXK01", "npda_code": "PZ223"},
    {"ods_code": "RWP50", "npda_code": "PZ225"},
    {"ods_code": "RXF10", "npda_code": "PZ226"},
    {"ods_code": "RXC", "npda_code": "PZ230"},
    {"ods_code": "RM301", "npda_code": "PZ231"},  # Salford Royal Hospital
    {"ods_code": "RF4", "npda_code": "PZ232"},
    {"ods_code": "RHU03", "npda_code": "PZ238"},
    {"ods_code": "RNA01", "npda_code": "PZ240"},
    {"ods_code": "RTE01", "npda_code": "PZ242"},
    {
        "ods_code": "RGT1W",
        "npda_code": "PZ248",
    },  # Jersey General Hospital added 22/6/24
    # Welsh PDUs
    {"ods_code": "7A3C7", "npda_code": "PZ001"},  # Morriston Hospital Swansea
    {"ods_code": "7A1A1", "npda_code": "PZ011"},  # Glan Clwyd District General Hospital
    {"ods_code": "7A3B7", "npda_code": "PZ092"},  # Princess of Wales Hospital, Bridgend
    {"ods_code": "7A4H1", "npda_code": "PZ113"},  # University Hospital of Wales
    {"ods_code": "7A1AU", "npda_code": "PZ132"},  # Ysbyty Gwynedd Hospital
    {"ods_code": "7A1A4", "npda_code": "PZ187"},  # Wrexham Maelor Hospital
    {"ods_code": "7A5B1", "npda_code": "PZ189"},  # Royal Glamorgan Hospital
    {"ods_code": "7A3CJ", "npda_code": "PZ193"},  # Neath Port Talbot Hospital
    {"ods_code": "7A5B3", "npda_code": "PZ228"},  # Prince Charles Hospital
    {"ods_code": "7A2", "npda_code": "PZ244"},  # Hywel Dda University Health Board
    {"ods_code": "7A6G9", "npda_code": "PZ245"},  # The Grange University Hospital
    {"ods_code": "8HV48", "npda_code": "PZ999"},  # RCPCH
]

# This is the same list but with the network names added. Keeping the old list as comments are available for each entry in the first list
PZ_CODES_NETWORKS = [
    {
        "ods_code": "RM102",
        "npda_code": "PZ002",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RXF05",
        "npda_code": "PZ003",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RNS01",
        "npda_code": "PZ004",
        "network_name": "East Midlands",
        "network_code": "PN09",
    },
    {
        "ods_code": "RTGFG",
        "npda_code": "PZ005",
        "network_name": "East Midlands",
        "network_code": "PN09",
    },
    {
        "ods_code": "RP5DR",
        "npda_code": "PZ006",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RTH08",
        "npda_code": "PZ007",
        "network_name": "Thames Valley",
        "network_code": "PN04",
    },
    {
        "ods_code": "RJN71",
        "npda_code": "PZ009",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RC971",
        "npda_code": "PZ010",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RAL26",
        "npda_code": "PZ012",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RALC7",
        "npda_code": "PZ014",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RM325",
        "npda_code": "PZ015",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RP5BA",
        "npda_code": "PZ016",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RBD01",
        "npda_code": "PZ017",
        "network_name": "South Central",
        "network_code": "PN03",
    },
    {
        "ods_code": "RYR18",
        "npda_code": "PZ018",
        "network_name": "South Central",
        "network_code": "PN03",
    },
    {
        "ods_code": "RAJ12",
        "npda_code": "PZ019",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RJL30",
        "npda_code": "PZ020",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RDU50",
        "npda_code": "PZ021",
        "network_name": "Thames Valley",
        "network_code": "PN04",
    },
    {
        "ods_code": "RNNBX",
        "npda_code": "PZ022",
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    },
    {
        "ods_code": "RJ701",
        "npda_code": "PZ023",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RVV",
        "npda_code": "PZ024",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RWA01",
        "npda_code": "PZ026",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RTR45",
        "npda_code": "PZ027",
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    },
    {
        "ods_code": "RXQ02",
        "npda_code": "PZ028",
        "network_name": "Thames Valley",
        "network_code": "PN04",
    },
    {
        "ods_code": "RBT20",
        "npda_code": "PZ030",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RYR16",
        "npda_code": "PZ031",
        "network_name": "South Central",
        "network_code": "PN03",
    },
    {
        "ods_code": "RTD02",
        "npda_code": "PZ032",
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    },
    {
        "ods_code": "RTG02",
        "npda_code": "PZ033",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RN541",
        "npda_code": "PZ034",
        "network_name": "South Central",
        "network_code": "PN03",
    },
    {
        "ods_code": "RHW01",
        "npda_code": "PZ035",
        "network_name": "Thames Valley",
        "network_code": "PN04",
    },
    {
        "ods_code": "R1HKH",
        "npda_code": "PZ036",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RXQ50",
        "npda_code": "PZ038",
        "network_name": "Thames Valley",
        "network_code": "PN04",
    },
    {
        "ods_code": "RRK97",
        "npda_code": "PZ040",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RGT01",
        "npda_code": "PZ041",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RX1RA",
        "npda_code": "PZ042",
        "network_name": "East Midlands",
        "network_code": "PN09",
    },
    {
        "ods_code": "RKEQ4",
        "npda_code": "PZ045",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RCF22",
        "npda_code": "PZ047",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RWDDA",
        "npda_code": "PZ048",
        "network_name": "East Midlands",
        "network_code": "PN09",
    },
    {
        "ods_code": "RWWWH",
        "npda_code": "PZ049",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RVR",
        "npda_code": "PZ050",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RJL32",
        "npda_code": "PZ053",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "R0D01",
        "npda_code": "PZ054",
        "network_name": "South Central",
        "network_code": "PN03",
    },
    {
        "ods_code": "RWEAA",
        "npda_code": "PZ055",
        "network_name": "East Midlands",
        "network_code": "PN09",
    },
    {
        "ods_code": "RAX01",
        "npda_code": "PZ057",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "R1HNH",
        "npda_code": "PZ058",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "R1H12",
        "npda_code": "PZ059",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RH801",
        "npda_code": "PZ060",
        "network_name": "South West",
        "network_code": "PN02",
    },
    {
        "ods_code": "RJ611",
        "npda_code": "PZ062",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RFSDA",
        "npda_code": "PZ064",
        "network_name": "East Midlands",
        "network_code": "PN09",
    },
    {
        "ods_code": "RJE09",
        "npda_code": "PZ065",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "REF12",
        "npda_code": "PZ067",
        "network_name": "South West",
        "network_code": "PN02",
    },
    {
        "ods_code": "RD130",
        "npda_code": "PZ068",
        "network_name": "South West",
        "network_code": "PN02",
    },
    {
        "ods_code": "RWJ09",
        "npda_code": "PZ069",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RGR50",
        "npda_code": "PZ072",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RWP01",
        "npda_code": "PZ073",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RBS25",
        "npda_code": "PZ074",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "R1F01",
        "npda_code": "PZ075",
        "network_name": "South Central",
        "network_code": "PN03",
    },
    {
        "ods_code": "RDEE4",
        "npda_code": "PZ076",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RJE01",
        "npda_code": "PZ078",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "R0B01",
        "npda_code": "PZ080",
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    },
    {
        "ods_code": "RJ122",
        "npda_code": "PZ082",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RWP31",
        "npda_code": "PZ084",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RJZ30",
        "npda_code": "PZ085",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RGN90",
        "npda_code": "PZ086",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RA201",
        "npda_code": "PZ088",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "R1K01",
        "npda_code": "PZ089",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RXR20",
        "npda_code": "PZ091",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RXWAT",
        "npda_code": "PZ094",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RK950",
        "npda_code": "PZ096",
        "network_name": "South West",
        "network_code": "PN02",
    },
    {
        "ods_code": "RXK02",
        "npda_code": "PZ097",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RWH",
        "npda_code": "PZ099",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RH880",
        "npda_code": "PZ100",
        "network_name": "South West",
        "network_code": "PN02",
    },
    {
        "ods_code": "RR801",
        "npda_code": "PZ101",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RAS01",
        "npda_code": "PZ102",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RRF02",
        "npda_code": "PZ104",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RAE05",
        "npda_code": "PZ105",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RXL01",
        "npda_code": "PZ106",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RR7EN",
        "npda_code": "PZ107",
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    },
    {
        "ods_code": "RQ301",
        "npda_code": "PZ108",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RHM01",
        "npda_code": "PZ109",
        "network_name": "South Central",
        "network_code": "PN03",
    },
    {
        "ods_code": "RVY02",
        "npda_code": "PZ110",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RLQ01",
        "npda_code": "PZ111",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RCBCA",
        "npda_code": "PZ112",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RCB55",
        "npda_code": "PZ114",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RJ224",
        "npda_code": "PZ118",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RN707",
        "npda_code": "PZ119",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RTFFS",
        "npda_code": "PZ120",
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    },
    {
        "ods_code": "RLT09",
        "npda_code": "PZ121",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RKB01",
        "npda_code": "PZ122",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RWF03",
        "npda_code": "PZ125",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RPA02",
        "npda_code": "PZ126",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RGP75",
        "npda_code": "PZ127",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RWDLA",
        "npda_code": "PZ128",
        "network_name": "East Midlands",
        "network_code": "PN09",
    },
    {
        "ods_code": "RCD01",
        "npda_code": "PZ129",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RQM01",
        "npda_code": "PZ130",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RGN80",
        "npda_code": "PZ131",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RTRAT",
        "npda_code": "PZ133",
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    },
    {
        "ods_code": "G0W1C",
        "npda_code": "PZ135",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "R0A",
        "npda_code": "PZ136",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RH5A8",
        "npda_code": "PZ137",
        "network_name": "South West",
        "network_code": "PN02",
    },
    {
        "ods_code": "RJC02",
        "npda_code": "PZ138",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RA723",
        "npda_code": "PZ139",
        "network_name": "South West",
        "network_code": "PN02",
    },
    {
        "ods_code": "RMP01",
        "npda_code": "PZ140",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "R0B0Q",
        "npda_code": "PZ141",
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    },
    {
        "ods_code": "RRK98",
        "npda_code": "PZ144",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RD816",
        "npda_code": "PZ145",
        "network_name": "Thames Valley",
        "network_code": "PN04",
    },
    {
        "ods_code": "RAJ01",
        "npda_code": "PZ146",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RFFAA",
        "npda_code": "PZ149",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RNN62",
        "npda_code": "PZ150",
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    },
    {
        "ods_code": "RJ231",
        "npda_code": "PZ151",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RA901",
        "npda_code": "PZ152",
        "network_name": "South West",
        "network_code": "PN02",
    },
    {
        "ods_code": "RBN01",
        "npda_code": "PZ153",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RCX70",
        "npda_code": "PZ156",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RAL01",
        "npda_code": "PZ157",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RN506",
        "npda_code": "PZ159",
        "network_name": "South Central",
        "network_code": "PN03",
    },
    {
        "ods_code": "RXPBA",
        "npda_code": "PZ160",
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    },
    {
        "ods_code": "RXPDA",
        "npda_code": "PZ161",
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    },
    {
        "ods_code": "RXPCP",
        "npda_code": "PZ162",
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    },
    {
        "ods_code": "RVWAE",
        "npda_code": "PZ163",
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    },
    {
        "ods_code": "RFRPA",
        "npda_code": "PZ164",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RTX",
        "npda_code": "PZ167",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RWDLP",
        "npda_code": "PZ168",
        "network_name": "East Midlands",
        "network_code": "PN09",
    },
    {
        "ods_code": "RNZ02",
        "npda_code": "PZ169",
        "network_name": "South Central",
        "network_code": "PN03",
    },
    {
        "ods_code": "RBL14",
        "npda_code": "PZ170",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "R1LCT",
        "npda_code": "PZ171",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RWG02",
        "npda_code": "PZ172",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RA430",
        "npda_code": "PZ173",
        "network_name": "South West",
        "network_code": "PN02",
    },
    {
        "ods_code": "RNQ51",
        "npda_code": "PZ174",
        "network_name": "East Midlands",
        "network_code": "PN09",
    },
    {
        "ods_code": "RTK01",
        "npda_code": "PZ176",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RMC01",
        "npda_code": "PZ177",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RBK02",
        "npda_code": "PZ178",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RJR",
        "npda_code": "PZ179",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RK5BC",
        "npda_code": "PZ180",
        "network_name": "East Midlands",
        "network_code": "PN09",
    },
    {
        "ods_code": "RDE03",
        "npda_code": "PZ181",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RQM91",
        "npda_code": "PZ182",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RXN02",
        "npda_code": "PZ183",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RWY",
        "npda_code": "PZ186",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "R1K04",
        "npda_code": "PZ191",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RP401",
        "npda_code": "PZ196",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RAPNM",
        "npda_code": "PZ199",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RQWG0",
        "npda_code": "PZ200",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RYJ01",
        "npda_code": "PZ202",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RRV03",
        "npda_code": "PZ203",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RM3",  # Salford Royal Hospital is the parent, Pennine Acute Hospitals NHS Trust - the PZ code is currently not in use
        "npda_code": "PZ206",
        "network_name": "Unknown",
        "network_code": None,
    },
    {
        "ods_code": "RTP04",
        "npda_code": "PZ213",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RJZ01",
        "npda_code": "PZ215",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RWFTW",
        "npda_code": "PZ216",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RDU01",
        "npda_code": "PZ218",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RCUEF",
        "npda_code": "PZ219",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RC979",
        "npda_code": "PZ220",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RGT2X",
        "npda_code": "PZ010",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RN325",
        "npda_code": "PZ221",
        "network_name": "South West",
        "network_code": "PN02",
    },
    {
        "ods_code": "RL403",
        "npda_code": "PZ222",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RXK01",
        "npda_code": "PZ223",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RWP50",
        "npda_code": "PZ225",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RXF10",
        "npda_code": "PZ226",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RXC",
        "npda_code": "PZ230",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RM301",
        "npda_code": "PZ231",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RF4",
        "npda_code": "PZ232",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RHU03",
        "npda_code": "PZ238",
        "network_name": "South Central",
        "network_code": "PN03",
    },
    {
        "ods_code": "RNA01",
        "npda_code": "PZ240",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RTE01",
        "npda_code": "PZ242",
        "network_name": "South West",
        "network_code": "PN02",
    },
    {
        "ods_code": "RGT1W",
        "npda_code": "PZ248",
        "network_name": "Jersey",
        "network_code": "PN01",
    },
    {
        "ods_code": "7A3C7",
        "npda_code": "PZ001",
        "network_name": "Wales",
        "network_code": "PN07",
    },
    {
        "ods_code": "7A1A1",
        "npda_code": "PZ011",
        "network_name": "Wales",
        "network_code": "PN07",
    },
    {
        "ods_code": "7A3B7",
        "npda_code": "PZ092",
        "network_name": "Wales",
        "network_code": "PN07",
    },
    {
        "ods_code": "7A4H1",
        "npda_code": "PZ113",
        "network_name": "Wales",
        "network_code": "PN07",
    },
    {
        "ods_code": "7A1AU",
        "npda_code": "PZ132",
        "network_name": "Wales",
        "network_code": "PN07",
    },
    {
        "ods_code": "7A1A4",
        "npda_code": "PZ187",
        "network_name": "Wales",
        "network_code": "PN07",
    },
    {
        "ods_code": "7A5B1",
        "npda_code": "PZ189",
        "network_name": "Wales",
        "network_code": "PN07",
    },
    {
        "ods_code": "7A3CJ",
        "npda_code": "PZ193",
        "network_name": "Wales",
        "network_code": "PN07",
    },
    {
        "ods_code": "7A5B3",
        "npda_code": "PZ228",
        "network_name": "Wales",
        "network_code": "PN07",
    },
    {
        "ods_code": "7A2",
        "npda_code": "PZ244",
        "network_name": "Wales",
        "network_code": "PN07",
    },
    {
        "ods_code": "7A6G9",
        "npda_code": "PZ245",
        "network_name": "Wales",
        "network_code": "PN07",
    },
    {
        "ods_code": "8HV48",
        "npda_code": "PZ999",
        "network_name": "Unknown",
        "network_code": None,
    },
]
