PZ_CODES = [
    {"ods_code": "RM102", "npda_code": "PZ002", "active": 1},
    {"ods_code": "RXF05", "npda_code": "PZ003", "active": 0},
    {"ods_code": "RNS01", "npda_code": "PZ004", "active": 1},
    {"ods_code": "RTGFG", "npda_code": "PZ005", "active": 1},
    {"ods_code": "RP5DR", "npda_code": "PZ006", "active": 1},
    {"ods_code": "RTH08", "npda_code": "PZ007", "active": 1},
    {"ods_code": "RJN71", "npda_code": "PZ009", "active": 1},
    {"ods_code": "RC971", "npda_code": "PZ010", "active": 1},
    {"ods_code": "RAL26", "npda_code": "PZ012", "active": 1},
    {"ods_code": "RALC7", "npda_code": "PZ014", "active": 1},
    {
        "ods_code": "RM325",
        "npda_code": "PZ015",
        "active": 1,
    },  # WYTHENSHAWE HOSPITAL (RM325 - parent UNIVERSITY HOSPITAL OF SOUTH MANCHESTER NHS FOUNDATION TRUST - RM2): this is the correct affiliation
    #  Note that it  has two ODS codes on the spine: the other is R0A07, parent Northern Care Alliance. This is incorrect. Note that Wythenshawe Hospital has a PZ code of PZ015,
    # which is different to the parent organisation ROA (whose children have PZ codes of PZ136)
    {"ods_code": "RP5BA", "npda_code": "PZ016", "active": 1},
    {"ods_code": "RBD01", "npda_code": "PZ017", "active": 1},
    {"ods_code": "RYR18", "npda_code": "PZ018", "active": 1},
    {"ods_code": "RAJ12", "npda_code": "PZ019", "active": 1},  # basildon formerly RDDH0
    {"ods_code": "RJL30", "npda_code": "PZ020", "active": 1},
    {"ods_code": "RDU50", "npda_code": "PZ021", "active": 1},
    {"ods_code": "RNNBX", "npda_code": "PZ022", "active": 1},
    {"ods_code": "RJ701", "npda_code": "PZ023", "active": 1},
    {"ods_code": "RVV", "npda_code": "PZ024", "active": 1},
    {"ods_code": "RWA01", "npda_code": "PZ026", "active": 1},
    {
        "ods_code": "RTR45",
        "npda_code": "PZ249",
        "active": 1,
    },  # PZ027 deprecated after merger updated 1/2/25
    {"ods_code": "RXQ02", "npda_code": "PZ028", "active": 1},
    {"ods_code": "RBT20", "npda_code": "PZ030", "active": 1},
    {"ods_code": "RYR16", "npda_code": "PZ031", "active": 1},
    {"ods_code": "RTD10", "npda_code": "PZ032", "active": 1},
    {"ods_code": "RTG02", "npda_code": "PZ033", "active": 1},
    {"ods_code": "RN541", "npda_code": "PZ034", "active": 1},
    {"ods_code": "RHW01", "npda_code": "PZ035", "active": 1},
    {"ods_code": "R1HKH", "npda_code": "PZ036", "active": 1},
    {"ods_code": "RXQ50", "npda_code": "PZ038", "active": 1},
    {"ods_code": "RRK97", "npda_code": "PZ040", "active": 1},
    {"ods_code": "RGT01", "npda_code": "PZ041", "active": 1},
    {"ods_code": "RX1RA", "npda_code": "PZ042", "active": 1, "unit_name": "NOTTINGHAM CHILDREN'S HOSPITAL"},
    {"ods_code": "RKEQ4", "npda_code": "PZ045", "active": 1},
    {"ods_code": "RCF22", "npda_code": "PZ047", "active": 1},
    {"ods_code": "RWDDA", "npda_code": "PZ048", "active": 1},
    {"ods_code": "RWWWH", "npda_code": "PZ049", "active": 1},
    {"ods_code": "RVR", "npda_code": "PZ050", "active": 1},
    {"ods_code": "RJL32", "npda_code": "PZ053", "active": 1},
    {
        "ods_code": "R0D01",
        "npda_code": "PZ054",
        "active": 1,
    },  # Poole Hospital formerly RD300
    {"ods_code": "RWEAA", "npda_code": "PZ055", "active": 1},
    {"ods_code": "RAX01", "npda_code": "PZ057", "active": 1},
    {"ods_code": "R1HNH", "npda_code": "PZ058", "active": 1},
    {"ods_code": "R1H12", "npda_code": "PZ059", "active": 1},
    {"ods_code": "RH801", "npda_code": "PZ060", "active": 1},
    {"ods_code": "RJ611", "npda_code": "PZ062", "active": 1},
    {"ods_code": "RFSDA", "npda_code": "PZ064", "active": 1},
    {"ods_code": "RJE09", "npda_code": "PZ065", "active": 1},
    {"ods_code": "REF12", "npda_code": "PZ067", "active": 1},
    {"ods_code": "RD130", "npda_code": "PZ068", "active": 1},
    {"ods_code": "RWJ09", "npda_code": "PZ069", "active": 1},
    {"ods_code": "RGR50", "npda_code": "PZ072", "active": 1},
    {"ods_code": "RWP01", "npda_code": "PZ073", "active": 1},
    {"ods_code": "RBS25", "npda_code": "PZ074", "active": 1},
    {"ods_code": "R1F01", "npda_code": "PZ075", "active": 1},
    {"ods_code": "RDEE4", "npda_code": "PZ076", "active": 1},
    {"ods_code": "RJE01", "npda_code": "PZ078", "active": 1},
    {"ods_code": "R0B01", "npda_code": "PZ080", "active": 0}, # deprecated 28/3/25 in favour of PZ250
    {"ods_code": "R0B01", "npda_code": "PZ250", "active": 1},
    {"ods_code": "RJ122", "npda_code": "PZ082", "active": 1, "unit_name": "EVELINA LONDON CHILDREN'S HOSPITAL"},
    {"ods_code": "RWP31", "npda_code": "PZ084", "active": 1},
    {"ods_code": "RJZ30", "npda_code": "PZ085", "active": 1},
    {"ods_code": "RGN90", "npda_code": "PZ086", "active": 1},
    {"ods_code": "RA201", "npda_code": "PZ088", "active": 1},
    {"ods_code": "R1K01", "npda_code": "PZ089", "active": 1},
    {"ods_code": "RXR20", "npda_code": "PZ091", "active": 1},
    {"ods_code": "RXWAT", "npda_code": "PZ094", "active": 1},
    {"ods_code": "RK950", "npda_code": "PZ096", "active": 1},
    {"ods_code": "RXK02", "npda_code": "PZ097", "active": 1},
    {"ods_code": "RWH20", "npda_code": "PZ099", "active": 1},
    {
        "ods_code": "RH880",
        "npda_code": "PZ100",
        "active": 1,
    },  # North Devon formerly RBZ12 til 1/3/22
    {"ods_code": "RR801", "npda_code": "PZ101", "active": 1},
    {"ods_code": "RAS01", "npda_code": "PZ102", "active": 1},
    {"ods_code": "RRF02", "npda_code": "PZ104", "active": 1},
    {"ods_code": "RAE05", "npda_code": "PZ105", "active": 1},
    {"ods_code": "RXL01", "npda_code": "PZ106", "active": 1},
    {"ods_code": "RR7EN", "npda_code": "PZ107", "active": 1},
    {"ods_code": "RQ301", "npda_code": "PZ108", "active": 1},
    {"ods_code": "RHM01", "npda_code": "PZ109", "active": 1},
    {"ods_code": "RVY02", "npda_code": "PZ110", "active": 1},
    {"ods_code": "RLQ01", "npda_code": "PZ111", "active": 1},
    {"ods_code": "RCBCA", "npda_code": "PZ112", "active": 1},
    {"ods_code": "RCB55", "npda_code": "PZ114", "active": 1},
    {"ods_code": "RJ224", "npda_code": "PZ118", "active": 1},
    {"ods_code": "RN707", "npda_code": "PZ119", "active": 1},
    {"ods_code": "RTFFS", "npda_code": "PZ120", "active": 1},
    {"ods_code": "RLT09", "npda_code": "PZ121", "active": 1},
    {"ods_code": "RKB01", "npda_code": "PZ122", "active": 1},
    {"ods_code": "RPA02", "npda_code": "PZ126", "active": 1},
    {"ods_code": "RGP75", "npda_code": "PZ127", "active": 1},
    {"ods_code": "RWDLA", "npda_code": "PZ128", "active": 1},
    {"ods_code": "RCD01", "npda_code": "PZ129", "active": 1},
    {"ods_code": "RQM01", "npda_code": "PZ130", "active": 1},
    {"ods_code": "RGN80", "npda_code": "PZ131", "active": 1},
    {
        "ods_code": "RTRAT",
        "npda_code": "PZ249",
        "active": 1,
    },  # PZ133 deprecated after merger updated 1/2/25
    {"ods_code": "G0W1C", "npda_code": "PZ135", "active": 1},  # Royal Alexandra
    {
        "ods_code": "R0A",
        "npda_code": "PZ136",
        "active": 1,
    },  # MANCHESTER UNIVERSITY NHS FOUNDATION TRUST is R0A.
    #  It's child organisations include MANCHESTER LOCAL CARE ORGANISATION (COX3P), NORTH MANCHESTER GENERAL HOSPITAL (R0A66),
    #  ROYAL MANCHESTER CHILDREN'S HOSPITAL (R0A03), TRAFFORD LOCAL CARE ORGANISATION (Q3K9W), WYTHENSHAWE HOSPITAL (RM325)
    # Note that Wythenshawe Hospital has a PZ code of PZ015, which is different to the parent organisation
    {
        "ods_code": "RH5A8",
        "npda_code": "PZ137",
        "active": 1,
    },  # Musgrove park formerly RBA11 til 31/3/2020
    {"ods_code": "RJC02", "npda_code": "PZ138", "active": 1},
    {"ods_code": "RA723", "npda_code": "PZ139", "active": 1},
    {"ods_code": "RMP01", "npda_code": "PZ140", "active": 1},
    {"ods_code": "R0B0Q", "npda_code": "PZ141", "active": 0}, # deprecated 28/3/25 in favour of PZ250
    {"ods_code": "R0B0Q", "npda_code": "PZ250", "active": 1},
    {"ods_code": "RRK98", "npda_code": "PZ144", "active": 1},
    {"ods_code": "RD816", "npda_code": "PZ145", "active": 1},
    {"ods_code": "RAJ01", "npda_code": "PZ146", "active": 1},
    {"ods_code": "RFFAA", "npda_code": "PZ149", "active": 1},
    {"ods_code": "RNN62", "npda_code": "PZ150", "active": 1},
    {"ods_code": "RJ231", "npda_code": "PZ151", "active": 1},
    {"ods_code": "RA901", "npda_code": "PZ152", "active": 1},
    {"ods_code": "RBN01", "npda_code": "PZ153", "active": 1},
    {"ods_code": "RCX70", "npda_code": "PZ156", "active": 1},
    {"ods_code": "RAL01", "npda_code": "PZ157", "active": 1},
    {"ods_code": "RN506", "npda_code": "PZ159", "active": 1},
    {"ods_code": "RXPBA", "npda_code": "PZ160", "active": 1},
    {"ods_code": "RXPDA", "npda_code": "PZ161", "active": 1},
    {"ods_code": "RXPCP", "npda_code": "PZ162", "active": 1},
    {"ods_code": "RVWAE", "npda_code": "PZ163", "active": 1},
    {"ods_code": "RFRPA", "npda_code": "PZ164", "active": 1},
    {"ods_code": "RTX", "npda_code": "PZ167", "active": 1},
    {"ods_code": "RWDLP", "npda_code": "PZ168", "active": 1},
    {"ods_code": "RNZ02", "npda_code": "PZ169", "active": 1},
    {"ods_code": "RBL14", "npda_code": "PZ170", "active": 1},
    {
        "ods_code": "R1LCT",
        "npda_code": "PZ171",
        "active": 1,
    },  # broomfield formerly RQ8L0 to 31/3/2020
    {"ods_code": "RWG02", "npda_code": "PZ172", "active": 1},
    {"ods_code": "RA430", "npda_code": "PZ173", "active": 1},
    {"ods_code": "RNQ51", "npda_code": "PZ174", "active": 1},
    {"ods_code": "RTK01", "npda_code": "PZ176", "active": 1},
    {"ods_code": "RMC01", "npda_code": "PZ177", "active": 1},
    {"ods_code": "RBK02", "npda_code": "PZ178", "active": 1},
    {"ods_code": "RJR", "npda_code": "PZ179", "active": 1},
    {"ods_code": "RK5BC", "npda_code": "PZ180", "active": 1},
    {"ods_code": "RDE03", "npda_code": "PZ181", "active": 1},
    {"ods_code": "RQM91", "npda_code": "PZ182", "active": 1},
    {"ods_code": "RXN02", "npda_code": "PZ183", "active": 1},
    {"ods_code": "RWY", "npda_code": "PZ186", "active": 1},
    {"ods_code": "R1K04", "npda_code": "PZ191", "active": 1},
    {"ods_code": "RP401", "npda_code": "PZ196", "active": 1},
    {"ods_code": "RAPNM", "npda_code": "PZ199", "active": 1},
    {"ods_code": "RQWG0", "npda_code": "PZ200", "active": 1},
    {"ods_code": "RYJ01", "npda_code": "PZ202", "active": 1},
    {"ods_code": "RRV03", "npda_code": "PZ203", "active": 1},
    {
        "ods_code": "RM3",
        "npda_code": "PZ206",
        "active": 0,
    },  # Pennine Acute Hospitals NHS Trust was RW6 and merged with Salford Royal NHS Foundation Trust, RM3 - currently not in use
    {"ods_code": "RTP04", "npda_code": "PZ213", "active": 1},
    {"ods_code": "RJZ01", "npda_code": "PZ215", "active": 1},
    {"ods_code": "RDU01", "npda_code": "PZ218", "active": 1},
    {"ods_code": "RCUEF", "npda_code": "PZ219", "active": 1},
    {"ods_code": "RC979", "npda_code": "PZ220", "active": 1},  # Bedford Hospital
    {
        "ods_code": "RC971",
        "npda_code": "PZ010",
        "active": 1,
    },  # Luton and Dunstable Hospital
    {"ods_code": "RN325", "npda_code": "PZ221", "active": 1},
    {"ods_code": "RL403", "npda_code": "PZ222", "active": 1},
    {"ods_code": "RXK01", "npda_code": "PZ223", "active": 1},
    {"ods_code": "RWP50", "npda_code": "PZ225", "active": 1},
    {"ods_code": "RXF10", "npda_code": "PZ226", "active": 1},
    {"ods_code": "RXC", "npda_code": "PZ230", "active": 1},
    {"ods_code": "RM301", "npda_code": "PZ231", "active": 1},  # Salford Royal Hospital
    {"ods_code": "RF4", "npda_code": "PZ232", "active": 1},
    {"ods_code": "RHU03", "npda_code": "PZ238", "active": 1},
    {"ods_code": "RNA01", "npda_code": "PZ240", "active": 1},
    {"ods_code": "RTE01", "npda_code": "PZ242", "active": 1},
    {"ods_code": "RTE03", "npda_code": "PZ242", "active": 1},
    {
        "ods_code": "RGT1W",
        "npda_code": "PZ248",
        "active": 1,
    },  # Jersey General Hospital added 22/6/24
    # Welsh PDUs
    {
        "ods_code": "7A3C7",
        "npda_code": "PZ001",
        "active": 1,
    },  # Morriston Hospital Swansea
    {
        "ods_code": "7A1A1",
        "npda_code": "PZ011",
        "active": 1,
    },  # Glan Clwyd District General Hospital
    {
        "ods_code": "7A3B7",
        "npda_code": "PZ092",
        "active": 1,
    },  # Princess of Wales Hospital, Bridgend
    {
        "ods_code": "7A4H1",
        "npda_code": "PZ113",
        "active": 1,
    },  # University Hospital of Wales
    {"ods_code": "7A1AU", "npda_code": "PZ132", "active": 1},  # Ysbyty Gwynedd Hospital
    {"ods_code": "7A1A4", "npda_code": "PZ187", "active": 1},  # Wrexham Maelor Hospital
    {
        "ods_code": "7A5B1",
        "npda_code": "PZ189",
        "active": 1,
    },  # Royal Glamorgan Hospital
    {
        "ods_code": "7A3CJ",
        "npda_code": "PZ193",
        "active": 1,
    },  # Neath Port Talbot Hospital
    {"ods_code": "7A5B3", "npda_code": "PZ228", "active": 1},  # Prince Charles Hospital
    {
        "ods_code": "7A2",
        "npda_code": "PZ244",
        "active": 1,
    },  # Hywel Dda University Health Board
    {
        "ods_code": "7A6G9",
        "npda_code": "PZ245",
        "active": 1,
    },  # The Grange University Hospital
    {
        "ods_code": "RXF05",
        "npda_code": "PZ251",
        "active": 1,
    },  # Pinderfields - new PZ code 5/4/25
    {
        "ods_code": "RXF3C",
        "npda_code": "PZ252",
        "active": 1,
    },  # Pontefract - new PZ code 5/4/25
    {
        "ods_code": "RM315",
        "npda_code": "PZ246",
        "active": 1,
    },
    {
        "ods_code": "RM316",
        "npda_code": "PZ246",
        "active": 1,
    },
    {
        "ods_code": "RM317",
        "npda_code": "PZ246",
        "active": 1,
    },
    # PZ216 and PZ125 merged into PZ253 (Jan 25)
    # https://github.com/rcpch/national-paediatric-diabetes-audit/issues/1292
    {
        "ods_code": "RWFTW",
        "npda_code": "PZ216",
        "active": 0
    },
    {
        "ods_code": "RWF03",
        "npda_code": "PZ125",
        "active": 0
    },
    {
        "ods_code": "RWFTW",
        "npda_code": "PZ253",
        "active": 1
    },
    {
        "ods_code": "RWF03",
        "npda_code": "PZ253",
        "active": 1
    },
    # PZ086 and PZ131 merged into PZ254 (for 26/27 audit year onwards)
    # https://github.com/rcpch/national-paediatric-diabetes-audit/issues/1349
    {
        "ods_code": "RGN80",
        "npda_code": "PZ254",
        "active": 1
    },
    {
        "ods_code": "RXN01",
        "npda_code": "PZ255",
        "active": 1
    },
    {
        "ods_code": "YK301",
        "npda_code": "PZ256",
        "active": 1
    },
    {"ods_code": "8HV48", "npda_code": "PZ999", "active": 1},  # RCPCH
]

# This is the same list but with the network names added. Keeping the old list as comments are available for each entry in the first list
PZ_CODES_NETWORKS = [
    {
        "ods_code": "RM102",
        "npda_code": "PZ002",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    # INACTIVE 05/04/25
    # Was PZ003 (Pinderfields General Hospital).
    # Split into PZ251 (Pinderfields General Hospital) and PZ252 (Pontefract General Infirmary).
    {
        "ods_code": "RXF05",  # PINDERFIELDS GENERAL HOSPITAL
        "npda_code": "PZ251",
        "npda_code": "PZ003",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RXF05",  # PINDERFIELDS GENERAL HOSPITAL
        "npda_code": "PZ251",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RL131",  # Pontefract General Infirmary
        "npda_code": "PZ251",
        # "npda_code": "PZ003", deprecated 5/4/2025
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RXF3C",  # PAEDIATRICS PONTEFRACT
        "npda_code": "PZ252",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RNS01",
        "npda_code": "PZ004",
        "network_name": "East Midlands",
        "network_code": "PN09",
    },
    {
        "ods_code": "RTGFG",
        "npda_code": "PZ005",
        "network_name": "East Midlands",
        "network_code": "PN09",
    },
    {
        "ods_code": "RP5DR",
        "npda_code": "PZ006",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RTH08",
        "npda_code": "PZ007",
        "network_name": "Thames Valley",
        "network_code": "PN04",
    },
    {
        "ods_code": "RJN71",
        "npda_code": "PZ009",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RC971",
        "npda_code": "PZ010",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RAL26",
        "npda_code": "PZ012",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RALC7",
        "npda_code": "PZ014",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RM325",
        "npda_code": "PZ015",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RP5BA",
        "npda_code": "PZ016",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RBD01",
        "npda_code": "PZ017",
        "network_name": "South Central",
        "network_code": "PN03",
    },
    {
        "ods_code": "RYR18",
        "npda_code": "PZ018",
        "network_name": "South Central",
        "network_code": "PN03",
    },
    {
        "ods_code": "RAJ12",
        "npda_code": "PZ019",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RJL30",
        "npda_code": "PZ020",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RDU50",
        "npda_code": "PZ021",
        "network_name": "Thames Valley",
        "network_code": "PN04",
    },
    {
        "ods_code": "RNNBX",
        "npda_code": "PZ022",
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    },
    {
        "ods_code": "RJ701",
        "npda_code": "PZ023",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RVV",
        "npda_code": "PZ024",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RWA01",
        "npda_code": "PZ026",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RTR45",
        "npda_code": "PZ249",
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    },
    {
        "ods_code": "RXQ02",
        "npda_code": "PZ028",
        "network_name": "Thames Valley",
        "network_code": "PN04",
    },
    {
        "ods_code": "RBT20",
        "npda_code": "PZ030",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RYR16",
        "npda_code": "PZ031",
        "network_name": "South Central",
        "network_code": "PN03",
    },
    {
        "ods_code": "RTD10",
        "npda_code": "PZ032",
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    },
    {
        "ods_code": "RTG02",
        "npda_code": "PZ033",
        "network_name": "East Midlands",
        "network_code": "PN09",
    },
    {
        "ods_code": "RN541",
        "npda_code": "PZ034",
        "network_name": "South Central",
        "network_code": "PN03",
    },
    {
        "ods_code": "RHW01",
        "npda_code": "PZ035",
        "network_name": "Thames Valley",
        "network_code": "PN04",
    },
    {
        "ods_code": "R1HKH",
        "npda_code": "PZ036",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RXQ50",
        "npda_code": "PZ038",
        "network_name": "Thames Valley",
        "network_code": "PN04",
    },
    {
        "ods_code": "RRK97",
        "npda_code": "PZ040",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RGT01",
        "npda_code": "PZ041",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RX1RA",
        "npda_code": "PZ042",
        "network_name": "East Midlands",
        "network_code": "PN09",
    },
    {
        "ods_code": "RKEQ4",
        "npda_code": "PZ045",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RCF22",
        "npda_code": "PZ047",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RWDDA",
        "npda_code": "PZ048",
        "network_name": "East Midlands",
        "network_code": "PN09",
    },
    {
        "ods_code": "RWWWH",
        "npda_code": "PZ049",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RVR",
        "npda_code": "PZ050",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RJL32",
        "npda_code": "PZ053",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "R0D01",
        "npda_code": "PZ054",
        "network_name": "South Central",
        "network_code": "PN03",
    },
    {
        "ods_code": "RWEAA",
        "npda_code": "PZ055",
        "network_name": "East Midlands",
        "network_code": "PN09",
    },
    {
        "ods_code": "RAX01",
        "npda_code": "PZ057",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "R1HNH",
        "npda_code": "PZ058",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "R1H12",
        "npda_code": "PZ059",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RH801",
        "npda_code": "PZ060",
        "network_name": "South West",
        "network_code": "PN02",
    },
    {
        "ods_code": "RJ611",
        "npda_code": "PZ062",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RFSDA",
        "npda_code": "PZ064",
        "network_name": "East Midlands",
        "network_code": "PN09",
    },
    {
        "ods_code": "RJE09",
        "npda_code": "PZ065",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "REF12",
        "npda_code": "PZ067",
        "network_name": "South West",
        "network_code": "PN02",
    },
    {
        "ods_code": "RD130",
        "npda_code": "PZ068",
        "network_name": "South West",
        "network_code": "PN02",
    },
    {
        "ods_code": "RWJ09",
        "npda_code": "PZ069",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RGR50",
        "npda_code": "PZ072",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RWP01",
        "npda_code": "PZ073",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RBS25",
        "npda_code": "PZ074",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "R1F01",
        "npda_code": "PZ075",
        "network_name": "South Central",
        "network_code": "PN03",
    },
    {
        "ods_code": "RDEE4",
        "npda_code": "PZ076",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RJE01",
        "npda_code": "PZ078",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "R0B01",
        "npda_code": "PZ080",
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    }, # deprecated 28/3/25 in favour of PZ250
    {
        "ods_code": "R0B01",
        "npda_code": "PZ250",
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    },
    {
        "ods_code": "RJ122",
        "npda_code": "PZ082",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RWP31",
        "npda_code": "PZ084",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RJZ30",
        "npda_code": "PZ085",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RGN90",
        "npda_code": "PZ086",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RA201",
        "npda_code": "PZ088",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "R1K01",
        "npda_code": "PZ089",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RXR20",
        "npda_code": "PZ091",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RXWAT",
        "npda_code": "PZ094",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RK950",
        "npda_code": "PZ096",
        "network_name": "South West",
        "network_code": "PN02",
    },
    {
        "ods_code": "RXK02",
        "npda_code": "PZ097",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RWH20",
        "npda_code": "PZ099",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RH880",
        "npda_code": "PZ100",
        "network_name": "South West",
        "network_code": "PN02",
    },
    {
        "ods_code": "RR801",
        "npda_code": "PZ101",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RAS01",
        "npda_code": "PZ102",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RRF02",
        "npda_code": "PZ104",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RAE05",
        "npda_code": "PZ105",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RXL01",
        "npda_code": "PZ106",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RR7EN",
        "npda_code": "PZ107",
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    },
    {
        "ods_code": "RQ301",
        "npda_code": "PZ108",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RHM01",
        "npda_code": "PZ109",
        "network_name": "South Central",
        "network_code": "PN03",
    },
    {
        "ods_code": "RVY02",
        "npda_code": "PZ110",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RLQ01",
        "npda_code": "PZ111",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RCBCA",
        "npda_code": "PZ112",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RCB55",
        "npda_code": "PZ114",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RJ224",
        "npda_code": "PZ118",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RN707",
        "npda_code": "PZ119",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RTFFS",
        "npda_code": "PZ120",
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    },
    {
        "ods_code": "RLT09",
        "npda_code": "PZ121",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RKB01",
        "npda_code": "PZ122",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RPA02",
        "npda_code": "PZ126",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RGP75",
        "npda_code": "PZ127",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RWDLA",
        "npda_code": "PZ128",
        "network_name": "East Midlands",
        "network_code": "PN09",
    },
    {
        "ods_code": "RCD01",
        "npda_code": "PZ129",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RQM01",
        "npda_code": "PZ130",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RGN80",
        "npda_code": "PZ131",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RTRAT",
        "npda_code": "PZ249",  # PZ133 deprecated after merger updated 1/2/25
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    },
    {
        "ods_code": "G0W1C",
        "npda_code": "PZ135",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "R0A",
        "npda_code": "PZ136",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RH5A8",
        "npda_code": "PZ137",
        "network_name": "South West",
        "network_code": "PN02",
    },
    {
        "ods_code": "RJC02",
        "npda_code": "PZ138",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RA723",
        "npda_code": "PZ139",
        "network_name": "South West",
        "network_code": "PN02",
    },
    {
        "ods_code": "RMP01",
        "npda_code": "PZ140",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "R0B0Q",
        "npda_code": "PZ141",
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    }, # deprecated 28/3/25 in favour of PZ250
    {
        "ods_code": "R0B0Q",
        "npda_code": "PZ250",
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    },
    {
        "ods_code": "RRK98",
        "npda_code": "PZ144",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RD816",
        "npda_code": "PZ145",
        "network_name": "Thames Valley",
        "network_code": "PN04",
    },
    {
        "ods_code": "RAJ01",
        "npda_code": "PZ146",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RFFAA",
        "npda_code": "PZ149",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RNN62",
        "npda_code": "PZ150",
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    },
    {
        "ods_code": "RJ231",
        "npda_code": "PZ151",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RA901",
        "npda_code": "PZ152",
        "network_name": "South West",
        "network_code": "PN02",
    },
    {
        "ods_code": "RBN01",
        "npda_code": "PZ153",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RCX70",
        "npda_code": "PZ156",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RAL01",
        "npda_code": "PZ157",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RN506",
        "npda_code": "PZ159",
        "network_name": "South Central",
        "network_code": "PN03",
    },
    {
        "ods_code": "RXPBA",
        "npda_code": "PZ160",
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    },
    {
        "ods_code": "RXPDA",
        "npda_code": "PZ161",
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    },
    {
        "ods_code": "RXPCP",
        "npda_code": "PZ162",
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    },
    {
        "ods_code": "RVWAE",
        "npda_code": "PZ163",
        "network_name": "North East & North Cumbria",
        "network_code": "PN12",
    },
    {
        "ods_code": "RFRPA",
        "npda_code": "PZ164",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RTX",
        "npda_code": "PZ167",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RWDLP",
        "npda_code": "PZ168",
        "network_name": "East Midlands",
        "network_code": "PN09",
    },
    {
        "ods_code": "RNZ02",
        "npda_code": "PZ169",
        "network_name": "South Central",
        "network_code": "PN03",
    },
    {
        "ods_code": "RBL14",
        "npda_code": "PZ170",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "R1LCT",
        "npda_code": "PZ171",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RWG02",
        "npda_code": "PZ172",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RA430",
        "npda_code": "PZ173",
        "network_name": "South West",
        "network_code": "PN02",
    },
    {
        "ods_code": "RNQ51",
        "npda_code": "PZ174",
        "network_name": "East Midlands",
        "network_code": "PN09",
    },
    {
        "ods_code": "RTK01",
        "npda_code": "PZ176",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RMC01",
        "npda_code": "PZ177",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RBK02",
        "npda_code": "PZ178",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RJR",
        "npda_code": "PZ179",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RK5BC",
        "npda_code": "PZ180",
        "network_name": "East Midlands",
        "network_code": "PN09",
    },
    {
        "ods_code": "RDE03",
        "npda_code": "PZ181",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RQM91",
        "npda_code": "PZ182",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RXN02",
        "npda_code": "PZ183",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RWY",
        "npda_code": "PZ186",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "R1K04",
        "npda_code": "PZ191",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RP401",
        "npda_code": "PZ196",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RAPNM",
        "npda_code": "PZ199",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RQWG0",
        "npda_code": "PZ200",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RYJ01",
        "npda_code": "PZ202",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RRV03",
        "npda_code": "PZ203",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RM3",  # Salford Royal Hospital is the parent, Pennine Acute Hospitals NHS Trust - the PZ code is currently not in use
        "npda_code": "PZ206",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RTP04",
        "npda_code": "PZ213",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RJZ01",
        "npda_code": "PZ215",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RDU01",
        "npda_code": "PZ218",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RCUEF",
        "npda_code": "PZ219",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RC979",
        "npda_code": "PZ220",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RC971",
        "npda_code": "PZ010",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RN325",
        "npda_code": "PZ221",
        "network_name": "South West",
        "network_code": "PN02",
    },
    {
        "ods_code": "RL403",
        "npda_code": "PZ222",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RXK01",
        "npda_code": "PZ223",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RWP50",
        "npda_code": "PZ225",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RXF10",
        "npda_code": "PZ226",
        "network_name": "Yorkshire & Humber",
        "network_code": "PN10",
    },
    {
        "ods_code": "RXC",
        "npda_code": "PZ230",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RM301",
        "npda_code": "PZ231",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "RF4",
        "npda_code": "PZ232",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RHU03",
        "npda_code": "PZ238",
        "network_name": "South Central",
        "network_code": "PN03",
    },
    {
        "ods_code": "RNA01",
        "npda_code": "PZ240",
        "network_name": "West Midlands",
        "network_code": "PN08",
    },
    {
        "ods_code": "RTE03",
        "npda_code": "PZ242",
        "network_name": "South West",
        "network_code": "PN02",
    },
    {
        "ods_code": "RGT1W",
        "npda_code": "PZ248",
        "network_name": "Jersey",
        "network_code": "PN01",
    },
    {
        "ods_code": "7A3C7",
        "npda_code": "PZ001",
        "network_name": "Wales",
        "network_code": "PN07",
    },
    {
        "ods_code": "7A1A1",
        "npda_code": "PZ011",
        "network_name": "Wales",
        "network_code": "PN07",
    },
    {
        "ods_code": "7A3B7",
        "npda_code": "PZ092",
        "network_name": "Wales",
        "network_code": "PN07",
    },
    {
        "ods_code": "7A4H1",
        "npda_code": "PZ113",
        "network_name": "Wales",
        "network_code": "PN07",
    },
    {
        "ods_code": "7A1AU",
        "npda_code": "PZ132",
        "network_name": "Wales",
        "network_code": "PN07",
    },
    {
        "ods_code": "7A1A4",
        "npda_code": "PZ187",
        "network_name": "Wales",
        "network_code": "PN07",
    },
    {
        "ods_code": "7A5B1",
        "npda_code": "PZ189",
        "network_name": "Wales",
        "network_code": "PN07",
    },
    {
        "ods_code": "7A3CJ",
        "npda_code": "PZ193",
        "network_name": "Wales",
        "network_code": "PN07",
    },
    {
        "ods_code": "7A5B3",
        "npda_code": "PZ228",
        "network_name": "Wales",
        "network_code": "PN07",
    },
    {
        "ods_code": "7A2",
        "npda_code": "PZ244",
        "network_name": "Wales",
        "network_code": "PN07",
    },
    {
        "ods_code": "7A6G9",
        "npda_code": "PZ245",
        "network_name": "Wales",
        "network_code": "PN07",
    },
    {
        "ods_code": "8HV48",  # RCPCH
        "npda_code": "PZ999",
        "network_name": "Unknown",
        "network_code": None,
    },
    {
        "ods_code": "RM317",
        "npda_code": "PZ246",
        "network_name": "North West",
        "network_code": "PN11",
    },  # Northern Care Alliance
    # PZ216 and PZ125 merged into PZ253 (Jan 25)
    # https://github.com/rcpch/national-paediatric-diabetes-audit/issues/1292
    {
        "ods_code": "RWFTW",
        "npda_code": "PZ216",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RWF03",
        "npda_code": "PZ125",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RWFTW",
        "npda_code": "PZ253",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    {
        "ods_code": "RWF03",
        "npda_code": "PZ253",
        "network_name": "London & South East",
        "network_code": "PN05",
    },
    # PZ086 and PZ131 merged into PZ254 (for 26/27 audit year onwards)
    # https://github.com/rcpch/national-paediatric-diabetes-audit/issues/1349
    {
        "ods_code": "RGN80",
        "npda_code": "PZ254",
        "network_name": "East of England",
        "network_code": "PN06",
    },
    {
        "ods_code": "RXN01",
        "npda_code": "PZ255",
        "network_name": "North West",
        "network_code": "PN11",
    },
    {
        "ods_code": "YK301",
        "npda_code": "PZ256",
        "network_name": "North West",
        "network_code": "PN11",
    }
]
