SCOTTISH_POSTCODES = [
    "KW1 4AA",
    "PA1 1AD",
    "FK1 1AA",
    "TD1 1AA",
    "G66 7HG",
    "DD1 1AA",
    "TD1 1AA",
    "ML1 1AA",
    "EH16 5QW",
    "EH1 1AD",
    "ML1 1AA",
    "PA1 1AD",
    "HS1 2AD",
    "IV1 1AA",
    "EH15 1NE",
    "G51 1DB",
    "EH47 0ST",
    "G22 7JL",
]

SCOTTISH_ADDRESSES = [
    {
        "query": "KW1 4AA",
        "result": {
            "postcode": "KW1 4AA",
            "quality": 1,
            "eastings": 336230,
            "northings": 951308,
            "country": "Scotland",
            "nhs_ha": "Highland",
            "longitude": -3.094157,
            "latitude": 58.445375,
            "european_electoral_region": "Scotland",
            "primary_care_trust": "Highland Health and Social Care Partnership",
            "region": None,
            "lsoa": "Wick North - 01",
            "msoa": "Wick North",
            "incode": "4AA",
            "outcode": "KW1",
            "parliamentary_constituency": "Caithness, Sutherland and Easter Ross",
            "admin_district": "Highland",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "198001",
            "admin_ward": "Wick and East Caithness",
            "ced": None,
            "ccg": "Highland Health and Social Care Partnership",
            "nuts": "Caithness and Sutherland, and Ross and Cromarty",
            "pfa": "Scotland",
            "codes": {
                "admin_district": "S12000017",
                "admin_county": "S99999999",
                "admin_ward": "S13002992",
                "parish": "S99999999",
                "parliamentary_constituency": "S14000009",
                "ccg": "S03000044",
                "ccg_id": "044",
                "ced": "S99999999",
                "nuts": "TLM61",
                "lsoa": "S01010782",
                "msoa": "S02002028",
                "lau2": "S30000029",
                "pfa": "S23000009",
            },
        },
    },
    {
        "query": "PA1 1AD",
        "result": {
            "postcode": "PA1 1AD",
            "quality": 1,
            "eastings": 248679,
            "northings": 663848,
            "country": "Scotland",
            "nhs_ha": "Greater Glasgow and Clyde",
            "longitude": -4.418295,
            "latitude": 55.844032,
            "european_electoral_region": "Scotland",
            "primary_care_trust": "Renfrewshire Community Health Partnership",
            "region": None,
            "lsoa": "Paisley Central - 02",
            "msoa": "Paisley Central",
            "incode": "1AD",
            "outcode": "PA1",
            "parliamentary_constituency": "Paisley and Renfrewshire South",
            "admin_district": "Renfrewshire",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "199207",
            "admin_ward": "Paisley East and Central",
            "ced": None,
            "ccg": "Renfrewshire Community Health Partnership",
            "nuts": "Inverclyde, East Renfrewshire, and Renfrewshire",
            "pfa": "Scotland",
            "codes": {
                "admin_district": "S12000038",
                "admin_county": "S99999999",
                "admin_ward": "S13003079",
                "parish": "S99999999",
                "parliamentary_constituency": "S14000053",
                "ccg": "S03000020",
                "ccg_id": "020",
                "ced": "S99999999",
                "nuts": "TLM83",
                "lsoa": "S01012127",
                "msoa": "S02002274",
                "lau2": "S30000021",
                "pfa": "S23000009",
            },
        },
    },
    {
        "query": "FK1 1AA",
        "result": {
            "postcode": "FK1 1AA",
            "quality": 1,
            "eastings": 288795,
            "northings": 680221,
            "country": "Scotland",
            "nhs_ha": "Forth Valley",
            "longitude": -3.784777,
            "latitude": 56.001996,
            "european_electoral_region": "Scotland",
            "primary_care_trust": "Falkirk Community Health Partnership",
            "region": None,
            "lsoa": "Falkirk - Grahamston - 03",
            "msoa": "Falkirk - Grahamston",
            "incode": "1AA",
            "outcode": "FK1",
            "parliamentary_constituency": "Falkirk",
            "admin_district": "Falkirk",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "198001",
            "admin_ward": "Falkirk South",
            "ced": None,
            "ccg": "Falkirk Community Health Partnership",
            "nuts": "Falkirk",
            "pfa": "Scotland",
            "codes": {
                "admin_district": "S12000014",
                "admin_county": "S99999999",
                "admin_ward": "S13002942",
                "parish": "S99999999",
                "parliamentary_constituency": "S14000028",
                "ccg": "S03000010",
                "ccg_id": "010",
                "ced": "S99999999",
                "nuts": "TLM76",
                "lsoa": "S01009140",
                "msoa": "S02001713",
                "lau2": "S30000009",
                "pfa": "S23000009",
            },
        },
    },
    {
        "query": "TD1 1AA",
        "result": {
            "postcode": "TD1 1AA",
            "quality": 1,
            "eastings": 349144,
            "northings": 636283,
            "country": "Scotland",
            "nhs_ha": "Borders",
            "longitude": -2.80901,
            "latitude": 55.617464,
            "european_electoral_region": "Scotland",
            "primary_care_trust": "Scottish Borders Community Health and Care Partnership",
            "region": None,
            "lsoa": "Galashiels - N - Town Centre",
            "msoa": "Galashiels North",
            "incode": "1AA",
            "outcode": "TD1",
            "parliamentary_constituency": "Berwickshire, Roxburgh and Selkirk",
            "admin_district": "Scottish Borders",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "199606",
            "admin_ward": "Galashiels and District",
            "ced": None,
            "ccg": "Scottish Borders Community Health & Care Partnership",
            "nuts": "Scottish Borders",
            "pfa": "Scotland",
            "codes": {
                "admin_district": "S12000026",
                "admin_county": "S99999999",
                "admin_ward": "S13002763",
                "parish": "S99999999",
                "parliamentary_constituency": "S14000008",
                "ccg": "S03000004",
                "ccg_id": "004",
                "ced": "S99999999",
                "nuts": "TLM91",
                "lsoa": "S01012275",
                "msoa": "S02002297",
                "lau2": "S30000007",
                "pfa": "S23000009",
            },
        },
    },
    {
        "query": "G66 7HG",
        "result": {
            "postcode": "G66 7HG",
            "quality": 1,
            "eastings": 262648,
            "northings": 678133,
            "country": "Scotland",
            "nhs_ha": "Greater Glasgow and Clyde",
            "longitude": -4.202668,
            "latitude": 55.976471,
            "european_electoral_region": "Scotland",
            "primary_care_trust": "East Dunbartonshire Community Health Partnership",
            "region": None,
            "lsoa": "Lennoxtown - 03",
            "msoa": "Lennoxtown",
            "incode": "7HG",
            "outcode": "G66",
            "parliamentary_constituency": "Cumbernauld, Kilsyth and Kirkintilloch East",
            "admin_district": "East Dunbartonshire",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "199812",
            "admin_ward": "Bishopbriggs North and Campsie",
            "ced": None,
            "ccg": "East Dunbartonshire Community Health Partnership",
            "nuts": "East Dunbartonshire, West Dunbartonshire, and Helensburgh and Lomond",
            "pfa": "Scotland",
            "codes": {
                "admin_district": "S12000045",
                "admin_county": "S99999999",
                "admin_ward": "S13002904",
                "parish": "S99999999",
                "parliamentary_constituency": "S14000012",
                "ccg": "S03000015",
                "ccg_id": "015",
                "ced": "S99999999",
                "nuts": "TLM81",
                "lsoa": "S01008160",
                "msoa": "S02001533",
                "lau2": "S30000050",
                "pfa": "S23000009",
            },
        },
    },
    {
        "query": "DD1 1AA",
        "result": {
            "postcode": "DD1 1AA",
            "quality": 1,
            "eastings": 340102,
            "northings": 730430,
            "country": "Scotland",
            "nhs_ha": "Tayside",
            "longitude": -2.973622,
            "latitude": 56.462189,
            "european_electoral_region": "Scotland",
            "primary_care_trust": "Dundee Community Health Partnership",
            "region": None,
            "lsoa": "City Centre - 05",
            "msoa": "City Centre",
            "incode": "1AA",
            "outcode": "DD1",
            "parliamentary_constituency": "Dundee West",
            "admin_district": "Dundee City",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "198001",
            "admin_ward": "Maryfield",
            "ced": None,
            "ccg": "Dundee Community Health Partnership",
            "nuts": "Angus and Dundee City",
            "pfa": "Scotland",
            "codes": {
                "admin_district": "S12000042",
                "admin_county": "S99999999",
                "admin_ward": "S13002549",
                "parish": "S99999999",
                "parliamentary_constituency": "S14000016",
                "ccg": "S03000039",
                "ccg_id": "039",
                "ced": "S99999999",
                "nuts": "TLM71",
                "lsoa": "S01007705",
                "msoa": "S02001448",
                "lau2": "S30000049",
                "pfa": "S23000009",
            },
        },
    },
    {
        "query": "TD1 1AA",
        "result": {
            "postcode": "TD1 1AA",
            "quality": 1,
            "eastings": 349144,
            "northings": 636283,
            "country": "Scotland",
            "nhs_ha": "Borders",
            "longitude": -2.80901,
            "latitude": 55.617464,
            "european_electoral_region": "Scotland",
            "primary_care_trust": "Scottish Borders Community Health and Care Partnership",
            "region": None,
            "lsoa": "Galashiels - N - Town Centre",
            "msoa": "Galashiels North",
            "incode": "1AA",
            "outcode": "TD1",
            "parliamentary_constituency": "Berwickshire, Roxburgh and Selkirk",
            "admin_district": "Scottish Borders",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "199606",
            "admin_ward": "Galashiels and District",
            "ced": None,
            "ccg": "Scottish Borders Community Health & Care Partnership",
            "nuts": "Scottish Borders",
            "pfa": "Scotland",
            "codes": {
                "admin_district": "S12000026",
                "admin_county": "S99999999",
                "admin_ward": "S13002763",
                "parish": "S99999999",
                "parliamentary_constituency": "S14000008",
                "ccg": "S03000004",
                "ccg_id": "004",
                "ced": "S99999999",
                "nuts": "TLM91",
                "lsoa": "S01012275",
                "msoa": "S02002297",
                "lau2": "S30000007",
                "pfa": "S23000009",
            },
        },
    },
    {
        "query": "ML1 1AA",
        "result": {
            "postcode": "ML1 1AA",
            "quality": 1,
            "eastings": 275021,
            "northings": 657387,
            "country": "Scotland",
            "nhs_ha": "Lanarkshire",
            "longitude": -3.994949,
            "latitude": 55.793568,
            "european_electoral_region": "Scotland",
            "primary_care_trust": "North Lanarkshire Community Health Partnership",
            "region": None,
            "lsoa": "Motherwell South - 03",
            "msoa": "Motherwell South",
            "incode": "1AA",
            "outcode": "ML1",
            "parliamentary_constituency": "Motherwell and Wishaw",
            "admin_district": "North Lanarkshire",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "198001",
            "admin_ward": "Motherwell North",
            "ced": None,
            "ccg": "North Lanarkshire Community Health Partnership",
            "nuts": "North Lanarkshire",
            "pfa": "Scotland",
            "codes": {
                "admin_district": "S12000050",
                "admin_county": "S99999999",
                "admin_ward": "S13003059",
                "parish": "S99999999",
                "parliamentary_constituency": "S14000047",
                "ccg": "S03000029",
                "ccg_id": "029",
                "ced": "S99999999",
                "nuts": "TLM84",
                "lsoa": "S01011473",
                "msoa": "S02002155",
                "lau2": "S30000053",
                "pfa": "S23000009",
            },
        },
    },
    {
        "query": "EH16 5QW",
        "result": {
            "postcode": "EH16 5QW",
            "quality": 1,
            "eastings": 327103,
            "northings": 670612,
            "country": "Scotland",
            "nhs_ha": "Lothian",
            "longitude": -3.168078,
            "latitude": 55.92304,
            "european_electoral_region": "Scotland",
            "primary_care_trust": "Edinburgh Community Health Partnership",
            "region": None,
            "lsoa": "Blackford, West Mains and Mayfield Road - 01",
            "msoa": "Blackford, West Mains and Mayfield Road",
            "incode": "5QW",
            "outcode": "EH16",
            "parliamentary_constituency": "Edinburgh South",
            "admin_district": "City of Edinburgh",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "198001",
            "admin_ward": "Southside/Newington",
            "ced": None,
            "ccg": "Edinburgh Community Health Partnership",
            "nuts": "City of Edinburgh",
            "pfa": "Scotland",
            "codes": {
                "admin_district": "S12000036",
                "admin_county": "S99999999",
                "admin_ward": "S13002933",
                "parish": "S99999999",
                "parliamentary_constituency": "S14000024",
                "ccg": "S03000042",
                "ccg_id": "042",
                "ced": "S99999999",
                "nuts": "TLM75",
                "lsoa": "S01008587",
                "msoa": "S02001609",
                "lau2": "S30000008",
                "pfa": "S23000009",
            },
        },
    },
    {
        "query": "EH1 1AD",
        "result": {
            "postcode": "EH1 1AD",
            "quality": 1,
            "eastings": 325610,
            "northings": 673543,
            "country": "Scotland",
            "nhs_ha": "Lothian",
            "longitude": -3.192773,
            "latitude": 55.949135,
            "european_electoral_region": "Scotland",
            "primary_care_trust": "Edinburgh Community Health Partnership",
            "region": None,
            "lsoa": "Old Town, Princes Street and Leith Street - 01",
            "msoa": "Old Town, Princes Street and Leith Street",
            "incode": "1AD",
            "outcode": "EH1",
            "parliamentary_constituency": "Edinburgh East",
            "admin_district": "City of Edinburgh",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "200906",
            "admin_ward": "City Centre",
            "ced": None,
            "ccg": "Edinburgh Community Health Partnership",
            "nuts": "City of Edinburgh",
            "pfa": "Scotland",
            "codes": {
                "admin_district": "S12000036",
                "admin_county": "S99999999",
                "admin_ward": "S13002929",
                "parish": "S99999999",
                "parliamentary_constituency": "S14000022",
                "ccg": "S03000042",
                "ccg_id": "042",
                "ced": "S99999999",
                "nuts": "TLM75",
                "lsoa": "S01008674",
                "msoa": "S02001622",
                "lau2": "S30000008",
                "pfa": "S23000009",
            },
        },
    },
    {
        "query": "ML1 1AA",
        "result": {
            "postcode": "ML1 1AA",
            "quality": 1,
            "eastings": 275021,
            "northings": 657387,
            "country": "Scotland",
            "nhs_ha": "Lanarkshire",
            "longitude": -3.994949,
            "latitude": 55.793568,
            "european_electoral_region": "Scotland",
            "primary_care_trust": "North Lanarkshire Community Health Partnership",
            "region": None,
            "lsoa": "Motherwell South - 03",
            "msoa": "Motherwell South",
            "incode": "1AA",
            "outcode": "ML1",
            "parliamentary_constituency": "Motherwell and Wishaw",
            "admin_district": "North Lanarkshire",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "198001",
            "admin_ward": "Motherwell North",
            "ced": None,
            "ccg": "North Lanarkshire Community Health Partnership",
            "nuts": "North Lanarkshire",
            "pfa": "Scotland",
            "codes": {
                "admin_district": "S12000050",
                "admin_county": "S99999999",
                "admin_ward": "S13003059",
                "parish": "S99999999",
                "parliamentary_constituency": "S14000047",
                "ccg": "S03000029",
                "ccg_id": "029",
                "ced": "S99999999",
                "nuts": "TLM84",
                "lsoa": "S01011473",
                "msoa": "S02002155",
                "lau2": "S30000053",
                "pfa": "S23000009",
            },
        },
    },
    {
        "query": "PA1 1AD",
        "result": {
            "postcode": "PA1 1AD",
            "quality": 1,
            "eastings": 248679,
            "northings": 663848,
            "country": "Scotland",
            "nhs_ha": "Greater Glasgow and Clyde",
            "longitude": -4.418295,
            "latitude": 55.844032,
            "european_electoral_region": "Scotland",
            "primary_care_trust": "Renfrewshire Community Health Partnership",
            "region": None,
            "lsoa": "Paisley Central - 02",
            "msoa": "Paisley Central",
            "incode": "1AD",
            "outcode": "PA1",
            "parliamentary_constituency": "Paisley and Renfrewshire South",
            "admin_district": "Renfrewshire",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "199207",
            "admin_ward": "Paisley East and Central",
            "ced": None,
            "ccg": "Renfrewshire Community Health Partnership",
            "nuts": "Inverclyde, East Renfrewshire, and Renfrewshire",
            "pfa": "Scotland",
            "codes": {
                "admin_district": "S12000038",
                "admin_county": "S99999999",
                "admin_ward": "S13003079",
                "parish": "S99999999",
                "parliamentary_constituency": "S14000053",
                "ccg": "S03000020",
                "ccg_id": "020",
                "ced": "S99999999",
                "nuts": "TLM83",
                "lsoa": "S01012127",
                "msoa": "S02002274",
                "lau2": "S30000021",
                "pfa": "S23000009",
            },
        },
    },
    {
        "query": "HS1 2AD",
        "result": {
            "postcode": "HS1 2AD",
            "quality": 1,
            "eastings": 142442,
            "northings": 932834,
            "country": "Scotland",
            "nhs_ha": "Western Isles",
            "longitude": -6.386334,
            "latitude": 58.208782,
            "european_electoral_region": "Scotland",
            "primary_care_trust": "Western Isles Community Health and Social Care Partnership",
            "region": None,
            "lsoa": "Stornoway West - 04",
            "msoa": "Stornoway West",
            "incode": "2AD",
            "outcode": "HS1",
            "parliamentary_constituency": "Na h-Eileanan an Iar",
            "admin_district": "Na h-Eileanan Siar",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "199507",
            "admin_ward": "Steornabhagh a Deas",
            "ced": None,
            "ccg": "Western Isles Community Health Partnership",
            "nuts": "Na h-Eileanan Siar",
            "pfa": "Scotland",
            "codes": {
                "admin_district": "S12000013",
                "admin_county": "S99999999",
                "admin_ward": "S13003141",
                "parish": "S99999999",
                "parliamentary_constituency": "S14000027",
                "ccg": "S03000041",
                "ccg_id": "041",
                "ced": "S99999999",
                "nuts": "TLM64",
                "lsoa": "S01009041",
                "msoa": "S02001693",
                "lau2": "S30000039",
                "pfa": "S23000009",
            },
        },
    },
    {"query": "IV1 1AA", "result": None},
    {
        "query": "EH15 1NE",
        "result": {
            "postcode": "EH15 1NE",
            "quality": 1,
            "eastings": 329854,
            "northings": 673383,
            "country": "Scotland",
            "nhs_ha": "Lothian",
            "longitude": -3.12479,
            "latitude": 55.948336,
            "european_electoral_region": "Scotland",
            "primary_care_trust": "Edinburgh Community Health Partnership",
            "region": None,
            "lsoa": "Duddingston and Portobello South - 01",
            "msoa": "Duddingston and Portobello South",
            "incode": "1NE",
            "outcode": "EH15",
            "parliamentary_constituency": "Edinburgh East",
            "admin_district": "City of Edinburgh",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "198001",
            "admin_ward": "Portobello/Craigmillar",
            "ced": None,
            "ccg": "Edinburgh Community Health Partnership",
            "nuts": "City of Edinburgh",
            "pfa": "Scotland",
            "codes": {
                "admin_district": "S12000036",
                "admin_county": "S99999999",
                "admin_ward": "S13002935",
                "parish": "S99999999",
                "parliamentary_constituency": "S14000022",
                "ccg": "S03000042",
                "ccg_id": "042",
                "ced": "S99999999",
                "nuts": "TLM75",
                "lsoa": "S01008734",
                "msoa": "S02001633",
                "lau2": "S30000008",
                "pfa": "S23000009",
            },
        },
    },
    {
        "query": "G51 1DB",
        "result": {
            "postcode": "G51 1DB",
            "quality": 1,
            "eastings": 256793,
            "northings": 664933,
            "country": "Scotland",
            "nhs_ha": "Greater Glasgow and Clyde",
            "longitude": -4.289399,
            "latitude": 55.85625,
            "european_electoral_region": "Scotland",
            "primary_care_trust": "Glasgow City Community Health Partnership",
            "region": None,
            "lsoa": "Ibrox East and Cessnock - 01",
            "msoa": "Ibrox East and Cessnock",
            "incode": "1DB",
            "outcode": "G51",
            "parliamentary_constituency": "Glasgow Central",
            "admin_district": "Glasgow City",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "201507",
            "admin_ward": "Govan",
            "ced": None,
            "ccg": "Glasgow City Community Health & Care Partnership",
            "nuts": "Glasgow City",
            "pfa": "Scotland",
            "codes": {
                "admin_district": "S12000049",
                "admin_county": "S99999999",
                "admin_ward": "S13002971",
                "parish": "S99999999",
                "parliamentary_constituency": "S14000029",
                "ccg": "S03000043",
                "ccg_id": "043",
                "ced": "S99999999",
                "nuts": "TLM82",
                "lsoa": "S01009862",
                "msoa": "S02001860",
                "lau2": "S30000052",
                "pfa": "S23000009",
            },
        },
    },
    {
        "query": "EH47 0ST",
        "result": {
            "postcode": "EH47 0ST",
            "quality": 1,
            "eastings": 293228,
            "northings": 664038,
            "country": "Scotland",
            "nhs_ha": "Lothian",
            "longitude": -3.707317,
            "latitude": 55.857664,
            "european_electoral_region": "Scotland",
            "primary_care_trust": "West Lothian Community Health and Care Partnership",
            "region": None,
            "lsoa": "Whitburn, Croftmalloch and Greenrigg - 03",
            "msoa": "Whitburn, Croftmalloch and Greenrigg",
            "incode": "0ST",
            "outcode": "EH47",
            "parliamentary_constituency": "Linlithgow and East Falkirk",
            "admin_district": "West Lothian",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "201803",
            "admin_ward": "Whitburn and Blackburn",
            "ced": None,
            "ccg": "West Lothian Community Health & Care Partnership",
            "nuts": "West Lothian",
            "pfa": "Scotland",
            "codes": {
                "admin_district": "S12000040",
                "admin_county": "S99999999",
                "admin_ward": "S13002826",
                "parish": "S99999999",
                "parliamentary_constituency": "S14000043",
                "ccg": "S03000035",
                "ccg_id": "035",
                "ced": "S99999999",
                "nuts": "TLM78",
                "lsoa": "S01013380",
                "msoa": "S02002499",
                "lau2": "S30000012",
                "pfa": "S23000009",
            },
        },
    },
    {
        "query": "G22 7JL",
        "result": {
            "postcode": "G22 7JL",
            "quality": 1,
            "eastings": 259713,
            "northings": 669569,
            "country": "Scotland",
            "nhs_ha": "Greater Glasgow and Clyde",
            "longitude": -4.245207,
            "latitude": 55.898736,
            "european_electoral_region": "Scotland",
            "primary_care_trust": "Glasgow City Community Health Partnership",
            "region": None,
            "lsoa": "Milton East - 04",
            "msoa": "Milton East",
            "incode": "7JL",
            "outcode": "G22",
            "parliamentary_constituency": "Glasgow North East",
            "admin_district": "Glasgow City",
            "parish": None,
            "admin_county": None,
            "date_of_introduction": "198001",
            "admin_ward": "Canal",
            "ced": None,
            "ccg": "Glasgow City Community Health & Care Partnership",
            "nuts": "Glasgow City",
            "pfa": "Scotland",
            "codes": {
                "admin_district": "S12000049",
                "admin_county": "S99999999",
                "admin_ward": "S13002982",
                "parish": "S99999999",
                "parliamentary_constituency": "S14000032",
                "ccg": "S03000043",
                "ccg_id": "043",
                "ced": "S99999999",
                "nuts": "TLM82",
                "lsoa": "S01010338",
                "msoa": "S02001944",
                "lau2": "S30000052",
                "pfa": "S23000009",
            },
        },
    },
]

SCOTTISH_IMD_TEST_DATA = [
    {
        "code:": "S01006506",
        "Data zone name": "Culter - 01",
        "Local authority": "Aberdeen City",
        "SIMD 2020v2 rank": "4691",
        "SIMD 2020v2 vigintile": "14",
        "SIMD 2020v2 decile": "7",
        "SIMD 2020v2 quintile": "4",
        "SIMD 2020v2 income rank": "3936",
        "SIMD 2020 employment rank": "3220",
        "SIMD 2020 education rank": "5887",
        "SIMD 2020 health rank": "5174",
        "SIMD 2020 access rank": "4724",
        "SIMD 2020 crime rank": "4664",
        "SIMD 2020 housing rank": "3248",
        "2017 Population": "894",
        "Working age population": "580",
        "Urban rural class": "Accessible Small Towns",
        "Intermediate zone": "Culter",
        "Health board": "Grampian",
        "Multi-member ward": "Lower Deeside",
        "Scottish parliamentary constituency": "Aberdeen South and North Kincardine",
    },
    {
        "code:": "S01010782",
        "Data zone name": "Wick North - 01",
        "Local authority": "Highland",
        "SIMD 2020v2 rank": "1555",
        "SIMD 2020v2 vigintile": "5",
        "SIMD 2020v2 decile": "3",
        "SIMD 2020v2 quintile": "2",
        "SIMD 2020v2 income rank": "1539",
        "SIMD 2020 employment rank": "1952",
        "SIMD 2020 education rank": "1499",
        "SIMD 2020 health rank": "1654",
        "SIMD 2020 access rank": "6588",
        "SIMD 2020 crime rank": "94",
        "SIMD 2020 housing rank": "2096",
        "2017 Population": "602",
        "Working age population": "349",
        "Urban rural class": "Remote Small Towns",
        "Intermediate zone": "Wick North",
        "Health board": "Highland",
        "Multi-member ward": "Wick and East Caithness",
        "Scottish parliamentary constituency": "Caithness, Sutherland and Ross",
    },
    {
        "code:": "S01012127",
        "Data zone name": "Paisley Central - 02",
        "Local authority": "Renfrewshire",
        "SIMD 2020v2 rank": "2124",
        "SIMD 2020v2 vigintile": "7",
        "SIMD 2020v2 decile": "4",
        "SIMD 2020v2 quintile": "2",
        "SIMD 2020v2 income rank": "2638",
        "SIMD 2020 employment rank": "2782",
        "SIMD 2020 education rank": "2114",
        "SIMD 2020 health rank": "2068",
        "SIMD 2020 access rank": "5775",
        "SIMD 2020 crime rank": "21",
        "SIMD 2020 housing rank": "243",
        "2017 Population": "1313",
        "Working age population": "1051",
        "Urban rural class": "Large Urban Areas",
        "Intermediate zone": "Paisley Central",
        "Health board": "Greater Glasgow and Clyde",
        "Multi-member ward": "Paisley Northeast and Ralston",
        "Scottish parliamentary constituency": "Paisley",
    },
    {
        "code:": "S01009140",
        "Data zone name": "Falkirk - Grahamston - 03",
        "Local authority": "Falkirk",
        "SIMD 2020v2 rank": "1481",
        "SIMD 2020v2 vigintile": "5",
        "SIMD 2020v2 decile": "3",
        "SIMD 2020v2 quintile": "2",
        "SIMD 2020v2 income rank": "1921",
        "SIMD 2020 employment rank": "1163",
        "SIMD 2020 education rank": "2576",
        "SIMD 2020 health rank": "1562",
        "SIMD 2020 access rank": "6048",
        "SIMD 2020 crime rank": "27",
        "SIMD 2020 housing rank": "2800",
        "2017 Population": "677",
        "Working age population": "479",
        "Urban rural class": "Other Urban Areas",
        "Intermediate zone": "Falkirk - Grahamston",
        "Health board": "Forth Valley",
        "Multi-member ward": "Falkirk North",
        "Scottish parliamentary constituency": "Falkirk West",
    },
    {
        "code:": "S01012275",
        "Data zone name": "Galashiels - N - Town Centre",
        "Local authority": "Scottish Borders",
        "SIMD 2020v2 rank": "1696",
        "SIMD 2020v2 vigintile": "5",
        "SIMD 2020v2 decile": "3",
        "SIMD 2020v2 quintile": "2",
        "SIMD 2020v2 income rank": "2270",
        "SIMD 2020 employment rank": "1721",
        "SIMD 2020 education rank": "1526",
        "SIMD 2020 health rank": "1684",
        "SIMD 2020 access rank": "6680",
        "SIMD 2020 crime rank": "74",
        "SIMD 2020 housing rank": "1188",
        "2017 Population": "781",
        "Working age population": "590",
        "Urban rural class": "Other Urban Areas",
        "Intermediate zone": "Galashiels North",
        "Health board": "Borders",
        "Multi-member ward": "Galashiels and District",
        "Scottish parliamentary constituency": "Midlothian South, Tweeddale and Lau",
    },
    {
        "code:": "S01008160",
        "Data zone name": "Lennoxtown - 03",
        "Local authority": "East Dunbartonshire",
        "SIMD 2020v2 rank": "2036",
        "SIMD 2020v2 vigintile": "6",
        "SIMD 2020v2 decile": "3",
        "SIMD 2020v2 quintile": "2",
        "SIMD 2020v2 income rank": "1610",
        "SIMD 2020 employment rank": "2145",
        "SIMD 2020 education rank": "2460",
        "SIMD 2020 health rank": "1569",
        "SIMD 2020 access rank": "3993",
        "SIMD 2020 crime rank": "3169",
        "SIMD 2020 housing rank": "3118",
        "2017 Population": "1027",
        "Working age population": "612",
        "Urban rural class": "Accessible Small Towns",
        "Intermediate zone": "Lennoxtown",
        "Health board": "Greater Glasgow and Clyde",
        "Multi-member ward": "Bishopbriggs North and Campsie",
        "Scottish parliamentary constituency": "Strathkelvin and Bearsden",
    },
    {
        "code:": "S01007705",
        "Data zone name": "City Centre - 05",
        "Local authority": "Dundee City",
        "SIMD 2020v2 rank": "1414",
        "SIMD 2020v2 vigintile": "5",
        "SIMD 2020v2 decile": "3",
        "SIMD 2020v2 quintile": "2",
        "SIMD 2020v2 income rank": "2126",
        "SIMD 2020 employment rank": "2082",
        "SIMD 2020 education rank": "1387",
        "SIMD 2020 health rank": "859",
        "SIMD 2020 access rank": "5593",
        "SIMD 2020 crime rank": "5",
        "SIMD 2020 housing rank": "177",
        "2017 Population": "793",
        "Working age population": "756",
        "Urban rural class": "Large Urban Areas",
        "Intermediate zone": "City Centre",
        "Health board": "Tayside",
        "Multi-member ward": "Maryfield",
        "Scottish parliamentary constituency": "Dundee City West",
    },
    {
        "code:": "S01012275",
        "Data zone name": "Galashiels - N - Town Centre",
        "Local authority": "Scottish Borders",
        "SIMD 2020v2 rank": "1696",
        "SIMD 2020v2 vigintile": "5",
        "SIMD 2020v2 decile": "3",
        "SIMD 2020v2 quintile": "2",
        "SIMD 2020v2 income rank": "2270",
        "SIMD 2020 employment rank": "1721",
        "SIMD 2020 education rank": "1526",
        "SIMD 2020 health rank": "1684",
        "SIMD 2020 access rank": "6680",
        "SIMD 2020 crime rank": "74",
        "SIMD 2020 housing rank": "1188",
        "2017 Population": "781",
        "Working age population": "590",
        "Urban rural class": "Other Urban Areas",
        "Intermediate zone": "Galashiels North",
        "Health board": "Borders",
        "Multi-member ward": "Galashiels and District",
        "Scottish parliamentary constituency": "Midlothian South, Tweeddale and Lau",
    },
    {
        "code:": "S01011473",
        "Data zone name": "Motherwell South - 03",
        "Local authority": "North Lanarkshire",
        "SIMD 2020v2 rank": "192",
        "SIMD 2020v2 vigintile": "1",
        "SIMD 2020v2 decile": "1",
        "SIMD 2020v2 quintile": "1",
        "SIMD 2020v2 income rank": "440",
        "SIMD 2020 employment rank": "121",
        "SIMD 2020 education rank": "354",
        "SIMD 2020 health rank": "138",
        "SIMD 2020 access rank": "5390",
        "SIMD 2020 crime rank": "32",
        "SIMD 2020 housing rank": "3075.5",
        "2017 Population": "714",
        "Working age population": "426",
        "Urban rural class": "Other Urban Areas",
        "Intermediate zone": "Motherwell South",
        "Health board": "Lanarkshire",
        "Multi-member ward": "Motherwell South East and Ravenscrai",
        "Scottish parliamentary constituency": "Motherwell and Wishaw",
    },
    {
        "code:": "S01008587",
        "Data zone name": "Blackford, West Mains and Mayfield Road - 0",
        "Local authority": "City of Edinburgh",
        "SIMD 2020v2 rank": "5588",
        "SIMD 2020v2 vigintile": "17",
        "SIMD 2020v2 decile": "9",
        "SIMD 2020v2 quintile": "5",
        "SIMD 2020v2 income rank": "5195.5",
        "SIMD 2020 employment rank": "6698",
        "SIMD 2020 education rank": "6006",
        "SIMD 2020 health rank": "5352",
        "SIMD 2020 access rank": "2338",
        "SIMD 2020 crime rank": "1058",
        "SIMD 2020 housing rank": "5630",
        "2017 Population": "1138",
        "Working age population": "797",
        "Urban rural class": "Large Urban Areas",
        "Intermediate zone": "Blackford, West Mains and Mayfield Road",
        "Health board": "Lothian",
        "Multi-member ward": "Southside/Newington",
        "Scottish parliamentary constituency": "Edinburgh Southern",
    },
    {
        "code:": "S01008674",
        "Data zone name": "Old Town, Princes Street and Leith Street -",
        "Local authority": "City of Edinburgh",
        "SIMD 2020v2 rank": "4105",
        "SIMD 2020v2 vigintile": "12",
        "SIMD 2020v2 decile": "6",
        "SIMD 2020v2 quintile": "3",
        "SIMD 2020v2 income rank": "5112",
        "SIMD 2020 employment rank": "4850",
        "SIMD 2020 education rank": "3471",
        "SIMD 2020 health rank": "5547",
        "SIMD 2020 access rank": "5637",
        "SIMD 2020 crime rank": "51",
        "SIMD 2020 housing rank": "52",
        "2017 Population": "1221",
        "Working age population": "1161",
        "Urban rural class": "Large Urban Areas",
        "Intermediate zone": "Old Town, Princes Street and Leith Street",
        "Health board": "Lothian",
        "Multi-member ward": "City Centre",
        "Scottish parliamentary constituency": "Edinburgh Central",
    },
    {
        "code:": "S01011473",
        "Data zone name": "Motherwell South - 03",
        "Local authority": "North Lanarkshire",
        "SIMD 2020v2 rank": "192",
        "SIMD 2020v2 vigintile": "1",
        "SIMD 2020v2 decile": "1",
        "SIMD 2020v2 quintile": "1",
        "SIMD 2020v2 income rank": "440",
        "SIMD 2020 employment rank": "121",
        "SIMD 2020 education rank": "354",
        "SIMD 2020 health rank": "138",
        "SIMD 2020 access rank": "5390",
        "SIMD 2020 crime rank": "32",
        "SIMD 2020 housing rank": "3075.5",
        "2017 Population": "714",
        "Working age population": "426",
        "Urban rural class": "Other Urban Areas",
        "Intermediate zone": "Motherwell South",
        "Health board": "Lanarkshire",
        "Multi-member ward": "Motherwell South East and Ravenscrai",
        "Scottish parliamentary constituency": "Motherwell and Wishaw",
    },
    {
        "code:": "S01012127",
        "Data zone name": "Paisley Central - 02",
        "Local authority": "Renfrewshire",
        "SIMD 2020v2 rank": "2124",
        "SIMD 2020v2 vigintile": "7",
        "SIMD 2020v2 decile": "4",
        "SIMD 2020v2 quintile": "2",
        "SIMD 2020v2 income rank": "2638",
        "SIMD 2020 employment rank": "2782",
        "SIMD 2020 education rank": "2114",
        "SIMD 2020 health rank": "2068",
        "SIMD 2020 access rank": "5775",
        "SIMD 2020 crime rank": "21",
        "SIMD 2020 housing rank": "243",
        "2017 Population": "1313",
        "Working age population": "1051",
        "Urban rural class": "Large Urban Areas",
        "Intermediate zone": "Paisley Central",
        "Health board": "Greater Glasgow and Clyde",
        "Multi-member ward": "Paisley Northeast and Ralston",
        "Scottish parliamentary constituency": "Paisley",
    },
    {
        "code:": "S01009041",
        "Data zone name": "Stornoway West - 04",
        "Local authority": "Na h-Eileanan Siar",
        "SIMD 2020v2 rank": "1938",
        "SIMD 2020v2 vigintile": "6",
        "SIMD 2020v2 decile": "3",
        "SIMD 2020v2 quintile": "2",
        "SIMD 2020v2 income rank": "1661",
        "SIMD 2020 employment rank": "1446",
        "SIMD 2020 education rank": "4194",
        "SIMD 2020 health rank": "2177",
        "SIMD 2020 access rank": "5870",
        "SIMD 2020 crime rank": "351",
        "SIMD 2020 housing rank": "4396",
        "2017 Population": "884",
        "Working age population": "551",
        "Urban rural class": "Remote Small Towns",
        "Intermediate zone": "Stornoway West",
        "Health board": "Western Isles",
        "Multi-member ward": "Steornabhagh a Deas",
        "Scottish parliamentary constituency": "Na h-Eileanan an Iar",
    },
    {
        "code:": "S01008734",
        "Data zone name": "Duddingston and Portobello South - 01",
        "Local authority": "City of Edinburgh",
        "SIMD 2020v2 rank": "4812",
        "SIMD 2020v2 vigintile": "14",
        "SIMD 2020v2 decile": "7",
        "SIMD 2020v2 quintile": "4",
        "SIMD 2020v2 income rank": "4415",
        "SIMD 2020 employment rank": "3544",
        "SIMD 2020 education rank": "5342",
        "SIMD 2020 health rank": "5189",
        "SIMD 2020 access rank": "5995",
        "SIMD 2020 crime rank": "1828",
        "SIMD 2020 housing rank": "3937",
        "2017 Population": "639",
        "Working age population": "349",
        "Urban rural class": "Large Urban Areas",
        "Intermediate zone": "Duddingston and Portobello South",
        "Health board": "Lothian",
        "Multi-member ward": "Portobello/Craigmillar",
        "Scottish parliamentary constituency": "Edinburgh Eastern",
    },
    {
        "code:": "S01009862",
        "Data zone name": "Ibrox East and Cessnock - 01",
        "Local authority": "Glasgow City",
        "SIMD 2020v2 rank": "401",
        "SIMD 2020v2 vigintile": "2",
        "SIMD 2020v2 decile": "1",
        "SIMD 2020v2 quintile": "1",
        "SIMD 2020v2 income rank": "555",
        "SIMD 2020 employment rank": "443",
        "SIMD 2020 education rank": "947",
        "SIMD 2020 health rank": "204",
        "SIMD 2020 access rank": "5719",
        "SIMD 2020 crime rank": "170",
        "SIMD 2020 housing rank": "121",
        "2017 Population": "1126",
        "Working age population": "829",
        "Urban rural class": "Large Urban Areas",
        "Intermediate zone": "Ibrox East and Cessnock",
        "Health board": "Greater Glasgow and Clyde",
        "Multi-member ward": "Govan",
        "Scottish parliamentary constituency": "Glasgow Southside",
    },
    {
        "code:": "S01013380",
        "Data zone name": "Whitburn, Croftmalloch and Greenrigg - 03",
        "Local authority": "West Lothian",
        "SIMD 2020v2 rank": "4536",
        "SIMD 2020v2 vigintile": "14",
        "SIMD 2020v2 decile": "7",
        "SIMD 2020v2 quintile": "4",
        "SIMD 2020v2 income rank": "4086.5",
        "SIMD 2020 employment rank": "4642",
        "SIMD 2020 education rank": "3376",
        "SIMD 2020 health rank": "2904",
        "SIMD 2020 access rank": "5187",
        "SIMD 2020 crime rank": "4398",
        "SIMD 2020 housing rank": "6273",
        "2017 Population": "1480",
        "Working age population": "1029",
        "Urban rural class": "Other Urban Areas",
        "Intermediate zone": "Whitburn, Croftmalloch and Greenrigg",
        "Health board": "Lothian",
        "Multi-member ward": "Whitburn and Blackburn",
        "Scottish parliamentary constituency": "Linlithgow",
    },
    {
        "code:": "S01010338",
        "Data zone name": "Milton East - 04",
        "Local authority": "Glasgow City",
        "SIMD 2020v2 rank": "122",
        "SIMD 2020v2 vigintile": "1",
        "SIMD 2020v2 decile": "1",
        "SIMD 2020v2 quintile": "1",
        "SIMD 2020v2 income rank": "225",
        "SIMD 2020 employment rank": "214",
        "SIMD 2020 education rank": "16",
        "SIMD 2020 health rank": "81",
        "SIMD 2020 access rank": "4981",
        "SIMD 2020 crime rank": "1187",
        "SIMD 2020 housing rank": "467",
        "2017 Population": "547",
        "Working age population": "349",
        "Urban rural class": "Large Urban Areas",
        "Intermediate zone": "Milton East",
        "Health board": "Greater Glasgow and Clyde",
        "Multi-member ward": "Canal",
        "Scottish parliamentary constituency": "Glasgow Maryhill and Springburn",
    },
]
