WELSH_POSTCODES = [
    "GL16 8PB",
    "NP10 0AA",
    "CF10 1AA",
    "SA1 1AA",
    "SY10 0AA",
    "LD1 5AB",
    "LD8 2RN",
    "CF14 3LX",
    "SA1 9TW",
    "NP25 5LD",
]

WELSH_ADDRESSES = [
    {
        "query": "GL16 8PB",
        "result": {
            "postcode": "GL16 8PB",
            "quality": 1,
            "eastings": 353334,
            "northings": 212382,
            "country": "Wales",
            "nhs_ha": "Aneurin Bevan University Health Board",
            "longitude": -2.678258,
            "latitude": 51.808116,
            "european_electoral_region": "Wales",
            "primary_care_trust": "Aneurin Bevan University Health Board",
            "region": None,
            "lsoa": "Monmouthshire 004F",
            "msoa": "Monmouthshire 004",
            "incode": "8PB",
            "outcode": "GL16",
            "parliamentary_constituency": "Monmouth",
            "admin_district": "Monmouthshire",
            "parish": "Monmouth",
            "admin_county": None,
            "date_of_introduction": "198001",
            "admin_ward": "Wyesham",
            "ced": None,
            "ccg": "Aneurin Bevan University",
            "nuts": "Monmouthshire and Newport",
            "pfa": "Gwent",
            "codes": {
                "admin_district": "W06000021",
                "admin_county": "W99999999",
                "admin_ward": "W05001800",
                "parish": "W04000799",
                "parliamentary_constituency": "W07000054",
                "ccg": "W11000028",
                "ccg_id": "7A6",
                "ced": "W99999999",
                "nuts": "TLL21",
                "lsoa": "W01001599",
                "msoa": "W02000339",
                "lau2": "W06000021",
                "pfa": "W15000002",
            },
        },
    },
    {
        "query": "NP10 0AA",
        "result": {
            "postcode": "NP10 0AA",
            "quality": 1,
            "eastings": 327203,
            "northings": 188953,
            "country": "Wales",
            "nhs_ha": "Aneurin Bevan University Health Board",
            "longitude": -3.052313,
            "latitude": 51.594701,
            "european_electoral_region": "Wales",
            "primary_care_trust": "Aneurin Bevan University Health Board",
            "region": None,
            "lsoa": "Newport 009A",
            "msoa": "Newport 009",
            "incode": "0AA",
            "outcode": "NP10",
            "parliamentary_constituency": "Newport West",
            "admin_district": "Newport",
            "parish": "Rogerstone",
            "admin_county": None,
            "date_of_introduction": "199906",
            "admin_ward": "Rogerstone North",
            "ced": None,
            "ccg": "Aneurin Bevan University",
            "nuts": "Monmouthshire and Newport",
            "pfa": "Gwent",
            "codes": {
                "admin_district": "W06000022",
                "admin_county": "W99999999",
                "admin_ward": "W05001641",
                "parish": "W04000830",
                "parliamentary_constituency": "W07000056",
                "ccg": "W11000028",
                "ccg_id": "7A6",
                "ced": "W99999999",
                "nuts": "TLL21",
                "lsoa": "W01001669",
                "msoa": "W02000355",
                "lau2": "W06000022",
                "pfa": "W15000002",
            },
        },
    },
    {
        "query": "CF10 1AA",
        "result": {
            "postcode": "CF10 1AA",
            "quality": 1,
            "eastings": 318284,
            "northings": 176230,
            "country": "Wales",
            "nhs_ha": "Cardiff and Vale University Health Board",
            "longitude": -3.178085,
            "latitude": 51.479102,
            "european_electoral_region": "Wales",
            "primary_care_trust": "Cardiff and Vale University Health Board",
            "region": None,
            "lsoa": "Cardiff 032G",
            "msoa": "Cardiff 032",
            "incode": "1AA",
            "outcode": "CF10",
            "parliamentary_constituency": "Cardiff Central",
            "admin_district": "Cardiff",
            "parish": "Castle",
            "admin_county": None,
            "date_of_introduction": "199906",
            "admin_ward": "Cathays",
            "ced": None,
            "ccg": "Cardiff and Vale University",
            "nuts": "Cardiff and Vale of Glamorgan",
            "pfa": "South Wales",
            "codes": {
                "admin_district": "W06000015",
                "admin_county": "W99999999",
                "admin_ward": "W05001274",
                "parish": "W04000841",
                "parliamentary_constituency": "W07000050",
                "ccg": "W11000029",
                "ccg_id": "7A4",
                "ced": "W99999999",
                "nuts": "TLL22",
                "lsoa": "W01001941",
                "msoa": "W02000398",
                "lau2": "W06000015",
                "pfa": "W15000003",
            },
        },
    },
    {
        "query": "SA1 1AA",
        "result": {
            "postcode": "SA1 1AA",
            "quality": 1,
            "eastings": 267010,
            "northings": 196107,
            "country": "Wales",
            "nhs_ha": "Swansea Bay University Health Board",
            "longitude": -3.923586,
            "latitude": 51.647984,
            "european_electoral_region": "Wales",
            "primary_care_trust": "Swansea Bay University Health Board",
            "region": None,
            "lsoa": "Swansea 014D",
            "msoa": "Swansea 014",
            "incode": "1AA",
            "outcode": "SA1",
            "parliamentary_constituency": "Swansea East",
            "admin_district": "Swansea",
            "parish": "Llansamlet",
            "admin_county": None,
            "date_of_introduction": "199002",
            "admin_ward": "Llansamlet",
            "ced": None,
            "ccg": "Swansea Bay University",
            "nuts": "Swansea",
            "pfa": "South Wales",
            "codes": {
                "admin_district": "W06000011",
                "admin_county": "W99999999",
                "admin_ward": "W05001052",
                "parish": "W04000969",
                "parliamentary_constituency": "W07000048",
                "ccg": "W11000031",
                "ccg_id": "7A3",
                "ced": "W99999999",
                "nuts": "TLL18",
                "lsoa": "W01000741",
                "msoa": "W02000181",
                "lau2": "W06000011",
                "pfa": "W15000003",
            },
        },
    },
    {
        "query": "SY10 0AA",
        "result": {
            "postcode": "SY10 0AA",
            "quality": 1,
            "eastings": 313006,
            "northings": 325603,
            "country": "Wales",
            "nhs_ha": "Powys Teaching Health Board",
            "longitude": -3.29238,
            "latitude": 52.820915,
            "european_electoral_region": "Wales",
            "primary_care_trust": "Powys Teaching Health Board",
            "region": None,
            "lsoa": "Powys 001F",
            "msoa": "Powys 001",
            "incode": "0AA",
            "outcode": "SY10",
            "parliamentary_constituency": "Montgomeryshire",
            "admin_district": "Powys",
            "parish": "Llanrhaeadr-ym-Mochnant",
            "admin_county": None,
            "date_of_introduction": "199906",
            "admin_ward": "Llanrhaeadr-ym-Mochnant and Llansilin",
            "ced": None,
            "ccg": "Powys Teaching",
            "nuts": "Powys",
            "pfa": "Dyfed-Powys",
            "codes": {
                "admin_district": "W06000023",
                "admin_county": "W99999999",
                "admin_ward": "W05001154",
                "parish": "W04000318",
                "parliamentary_constituency": "W07000063",
                "ccg": "W11000024",
                "ccg_id": "7A7",
                "ced": "W99999999",
                "nuts": "TLL24",
                "lsoa": "W01001906",
                "msoa": "W02000097",
                "lau2": "W06000023",
                "pfa": "W15000004",
            },
        },
    },
    {
        "query": "LD1 5AB",
        "result": {
            "postcode": "LD1 5AB",
            "quality": 1,
            "eastings": 306543,
            "northings": 262536,
            "country": "Wales",
            "nhs_ha": "Powys Teaching Health Board",
            "longitude": -3.370489,
            "latitude": 52.253032,
            "european_electoral_region": "Wales",
            "primary_care_trust": "Powys Teaching Health Board",
            "region": None,
            "lsoa": "Powys 013B",
            "msoa": "Powys 013",
            "incode": "5AB",
            "outcode": "LD1",
            "parliamentary_constituency": "Brecon and Radnorshire",
            "admin_district": "Powys",
            "parish": "Llandrindod Wells",
            "admin_county": None,
            "date_of_introduction": "200112",
            "admin_ward": "Llandrindod North",
            "ced": None,
            "ccg": "Powys Teaching",
            "nuts": "Powys",
            "pfa": "Dyfed-Powys",
            "codes": {
                "admin_district": "W06000023",
                "admin_county": "W99999999",
                "admin_ward": "W05001142",
                "parish": "W04000293",
                "parliamentary_constituency": "W07000068",
                "ccg": "W11000024",
                "ccg_id": "7A7",
                "ced": "W99999999",
                "nuts": "TLL24",
                "lsoa": "W01000455",
                "msoa": "W02000109",
                "lau2": "W06000023",
                "pfa": "W15000004",
            },
        },
    },
    {
        "query": "LD8 2RN",
        "result": {
            "postcode": "LD8 2RN",
            "quality": 1,
            "eastings": 324615,
            "northings": 258088,
            "country": "Wales",
            "nhs_ha": "Powys Teaching Health Board",
            "longitude": -3.104815,
            "latitude": 52.215827,
            "european_electoral_region": "Wales",
            "primary_care_trust": "Powys Teaching Health Board",
            "region": None,
            "lsoa": "Powys 011E",
            "msoa": "Powys 011",
            "incode": "2RN",
            "outcode": "LD8",
            "parliamentary_constituency": "Brecon and Radnorshire",
            "admin_district": "Powys",
            "parish": "Old Radnor",
            "admin_county": None,
            "date_of_introduction": "198001",
            "admin_ward": "Old Radnor",
            "ced": None,
            "ccg": "Powys Teaching",
            "nuts": "Powys",
            "pfa": "Dyfed-Powys",
            "codes": {
                "admin_district": "W06000023",
                "admin_county": "W99999999",
                "admin_ward": "W05001164",
                "parish": "W04000336",
                "parliamentary_constituency": "W07000068",
                "ccg": "W11000024",
                "ccg_id": "7A7",
                "ced": "W99999999",
                "nuts": "TLL24",
                "lsoa": "W01000484",
                "msoa": "W02000107",
                "lau2": "W06000023",
                "pfa": "W15000004",
            },
        },
    },
    {
        "query": "CF14 3LX",
        "result": {
            "postcode": "CF14 3LX",
            "quality": 1,
            "eastings": 317748,
            "northings": 178588,
            "country": "Wales",
            "nhs_ha": "Cardiff and Vale University Health Board",
            "longitude": -3.18636,
            "latitude": 51.500223,
            "european_electoral_region": "Wales",
            "primary_care_trust": "Cardiff and Vale University Health Board",
            "region": None,
            "lsoa": "Cardiff 025D",
            "msoa": "Cardiff 025",
            "incode": "3LX",
            "outcode": "CF14",
            "parliamentary_constituency": "Cardiff North",
            "admin_district": "Cardiff",
            "parish": "Gabalfa",
            "admin_county": None,
            "date_of_introduction": "199906",
            "admin_ward": "Gabalfa",
            "ced": None,
            "ccg": "Cardiff and Vale University",
            "nuts": "Cardiff and Vale of Glamorgan",
            "pfa": "South Wales",
            "codes": {
                "admin_district": "W06000015",
                "admin_county": "W99999999",
                "admin_ward": "W05001278",
                "parish": "W04000846",
                "parliamentary_constituency": "W07000051",
                "ccg": "W11000029",
                "ccg_id": "7A4",
                "ced": "W99999999",
                "nuts": "TLL22",
                "lsoa": "W01001758",
                "msoa": "W02000391",
                "lau2": "W06000015",
                "pfa": "W15000003",
            },
        },
    },
    {
        "query": "SA1 9TW",
        "result": {
            "postcode": "SA1 9TW",
            "quality": 1,
            "eastings": 265195,
            "northings": 192342,
            "country": "Wales",
            "nhs_ha": "Swansea Bay University Health Board",
            "longitude": -3.948352,
            "latitude": 51.613719,
            "european_electoral_region": "Wales",
            "primary_care_trust": "Swansea Bay University Health Board",
            "region": None,
            "lsoa": "Swansea 025E",
            "msoa": "Swansea 025",
            "incode": "9TW",
            "outcode": "SA1",
            "parliamentary_constituency": "Swansea West",
            "admin_district": "Swansea",
            "parish": "Castle",
            "admin_county": None,
            "date_of_introduction": "200502",
            "admin_ward": "Waterfront",
            "ced": None,
            "ccg": "Swansea Bay University",
            "nuts": "Swansea",
            "pfa": "South Wales",
            "codes": {
                "admin_district": "W06000011",
                "admin_county": "W99999999",
                "admin_ward": "W05001068",
                "parish": "W04000959",
                "parliamentary_constituency": "W07000047",
                "ccg": "W11000031",
                "ccg_id": "7A3",
                "ced": "W99999999",
                "nuts": "TLL18",
                "lsoa": "W01001938",
                "msoa": "W02000192",
                "lau2": "W06000011",
                "pfa": "W15000003",
            },
        },
    },
    {
        "query": "NP25 5LD",
        "result": {
            "postcode": "NP25 5LD",
            "quality": 1,
            "eastings": 350885,
            "northings": 214995,
            "country": "Wales",
            "nhs_ha": "Aneurin Bevan University Health Board",
            "longitude": -2.714151,
            "latitude": 51.831402,
            "european_electoral_region": "Wales",
            "primary_care_trust": "Aneurin Bevan University Health Board",
            "region": None,
            "lsoa": "Monmouthshire 004A",
            "msoa": "Monmouthshire 004",
            "incode": "5LD",
            "outcode": "NP25",
            "parliamentary_constituency": "Monmouth",
            "admin_district": "Monmouthshire",
            "parish": "Monmouth",
            "admin_county": None,
            "date_of_introduction": "199906",
            "admin_ward": "Osbaston",
            "ced": None,
            "ccg": "Aneurin Bevan University",
            "nuts": "Monmouthshire and Newport",
            "pfa": "Gwent",
            "codes": {
                "admin_district": "W06000021",
                "admin_county": "W99999999",
                "admin_ward": "W05001787",
                "parish": "W04000799",
                "parliamentary_constituency": "W07000054",
                "ccg": "W11000028",
                "ccg_id": "7A6",
                "ced": "W99999999",
                "nuts": "TLL21",
                "lsoa": "W01001552",
                "msoa": "W02000339",
                "lau2": "W06000021",
                "pfa": "W15000002",
            },
        },
    },
]
