"""
Django settings for rcpch_nhs_organisations project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

# standard imports
import os
from pathlib import Path

# third party imports
from django.core.management.utils import get_random_secret_key

# RCPCH imports
from .logging_settings import (
    LOGGING,
)  # no it is not an unused import, it pulls LOGGING into the settings file

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("RCPCH_NHS_ORGANISATIONS_SECRET_KEY", get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

if os.getenv("WEBSITE_SITE_NAME"):
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")

CSRF_TRUSTED_ORIGINS = os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")

# Enables Django to use the X-Forwarded-Host header in preference to the Host header.
# Fixes CSRF errors when using Caddy to forward requests to Django.
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Azure API Management (APIM) configuration.
# The API is served behind APIM with two APIs: a data API (subscription
# required) at APIM_DATA_API_PREFIX and a docs API (subscription off) at a
# /docs sub-suffix. See documentation/docs/developer/behind-apim.md.
APIM_DATA_API_PREFIX = os.getenv("APIM_DATA_API_PREFIX", "/nhs-organisations/v1")
# Where the docs API base URL redirects to (the project documentation site).
APIM_DOCS_REDIRECT_URL = os.getenv(
    "APIM_DOCS_REDIRECT_URL", "https://rcpch.github.io/rcpch-nhs-organisations/"
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "rest_framework",
    "rest_framework_gis",
    "django_filters",
    "drf_spectacular",
    "rcpch_nhs_organisations.hospitals",
]

MIDDLEWARE = [
    # Outermost so that SCRIPT_NAME/PATH_INFO are fixed up before
    # CommonMiddleware's APPEND_SLASH redirect and every URL is generated.
    # No-op when X-Forwarded-Prefix is absent (local dev, raw Azure URL).
    "rcpch_nhs_organisations.middleware.ForwardedPrefixMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "rcpch_nhs_organisations.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "rcpch_nhs_organisations.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": os.environ.get("POSTGRES_DB"),
        "USER": os.environ.get("POSTGRES_USER"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
        "PORT": os.environ.get("POSTGRES_PORT"),
        "HOST": os.environ.get("POSTGRES_HOST"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = (str(BASE_DIR.joinpath("static")),)
STATIC_ROOT = str(BASE_DIR.joinpath("staticfiles"))
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
WHITENOISE_ROOT = os.path.join(BASE_DIR, "static/root")

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": None,
    "DEFAULT_FILTER_BACKENDS": ("django_filters.rest_framework.DjangoFilterBackend",),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_CONTENT_NEGOTIATION_CLASS": "rcpch_nhs_organisations.negotiation.APIMAwareContentNegotiation",
}

# drf-spectacular schema settings
SPECTACULAR_SETTINGS = {
    "TITLE": "RCPCH NHS Organisations",
    "DESCRIPTION": "UK NHS Organisations responsible for children's health, as a service.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # Inject the APIM subscription key as an OpenAPI security scheme so
    # Swagger UI shows an Authorize button and sends the key on Try it out.
    # The hook is a no-op when the request did not come through APIM (no
    # X-Forwarded-Prefix header), so local dev / raw Azure URL show no locks.
    "POSTPROCESSING_HOOKS": [
        "drf_spectacular.hooks.postprocess_schema_enums",
        "rcpch_nhs_organisations.openapi_hooks.add_apim_subscription_key_security",
        "rcpch_nhs_organisations.openapi_hooks.set_servers_to_data_api",
    ],
    "SWAGGER_UI_FAVICON_HREF": STATIC_URL
    + "rcpch-logo.jpg",  # default is swagger favicon
    # Group endpoints into ordered, capitalised sections in Swagger UI.
    # The order of this list controls the display order in Swagger UI; each
    # viewset sets its tag via @extend_schema(tags=[...]).
    "TAGS": [
        {"name": "Organisations", "description": "NHS hospital sites (Organisations)."},
        {"name": "Trusts", "description": "NHS Trusts (England)."},
        {"name": "Local Health Boards", "description": "Local Health Boards (Wales)."},
        {"name": "Integrated Care Boards", "description": "Integrated Care Boards (England)."},
        {"name": "NHS England Regions", "description": "NHS England regions above ICBs."},
        {
            "name": "Child Health Geographies",
            "description": "Paediatric Diabetes Units and OPENUK (epilepsy) Networks.",
        },
        {
            "name": "Boundaries",
            "description": "Reference geographies: countries, London boroughs, local authority districts.",
        },
        {"name": "Other", "description": "Schema, Swagger UI, and other endpoints."},
    ],
    # OTHER SETTINGS
}
