# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - rcpch-nhs-organisations. Deploy docs to GitHub Pages

on:
  pull_request:
    branches:
      - live
    types:
      - closed

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true && !contains(github.event.pull_request.title, '[docs]')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true # ensures large files are downloaded using Git LFS

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2 # Update the version to v2
        with:
          app-name: "RCPCH-NHS-organisations"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A76B7421A08D44778EBB49AB30B51B3D }}
          package: "."

  deploy-mkdocs:
    if: github.event.pull_request.merged == true && !contains(github.event.pull_request.title, '[docs]')
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"

      - name: Install MkDocs and dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-git-committers-plugin-2 mkdocs-git-revision-date-localized-plugin mkdocs-macros-plugin mkdocs-with-pdf

      - name: Build MkDocs site
        env:
          SITE_DIR: documentation/site
          DOCS_URL: https://rcpch.github.io/rcpch-nhs-organisations/
        run: mkdocs build --config-file documentation/mkdocs.yml --verbose || exit 1

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: documentation/site

  deploy-mkdocs-only:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.title, '[docs]')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"

      - name: Install MkDocs and dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-git-committers-plugin-2 mkdocs-git-revision-date-localized-plugin mkdocs-macros-plugin mkdocs-with-pdf

      - name: Build MkDocs site
        env:
          SITE_DIR: documentation/site
          DOCS_URL: https://rcpch.github.io/rcpch-nhs-organisations/
        run: mkdocs build --config-file documentation/mkdocs.yml --verbose || exit 1

      - name: Verify MkDocs build output
        run: ls -la documentation/site || echo "MkDocs build failed or output directory is missing!"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: documentation/site
