# Runs the Pytest test suite when PRs are made against any branch

name: Run pr-check script on all PRs

on:
    pull_request:
      branches:
        - "*"

jobs:
  build-and-run-pytest-suite-in-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full code repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # to allow git_context_processor.py to still work

      - name: Create .env file from example
        run: cp envs/example.env envs/.env

      - name: Run pr-check script
        run: s/pr-check


